# Generated by Django 5.1 on 2026-04-09 06:03

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_Import_Model',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('layer_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'temp_import',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment_Ward_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=100)),
                ('org_id', models.IntegerField()),
            ],
            options={
                'db_table': 'assessment_ward',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City_Object_Model',
            fields=[
                ('city_object_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('parents', models.JSONField(blank=True, null=True)),
                ('children', models.JSONField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city_object',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CityJSON_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cityjson_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'city_json',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dynamic_Attribute_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('su_id', models.IntegerField()),
                ('section_key', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dynamic_attribute',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='History_Party_Attrib_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done_by', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'history_party_attrib',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='History_User_Attrib_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done_by', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'history_user_attrib',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_Admin_Source_Model',
            fields=[
                ('admin_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_source_type', models.CharField(max_length=255)),
                ('reference_no', models.CharField(max_length=255, null=True)),
                ('acceptance_date', models.DateField(null=True)),
                ('exte_arch_ref', models.CharField(max_length=255, null=True)),
                ('source_description', models.TextField(null=True)),
                ('done_by', models.IntegerField(null=True)),
                ('user_id', models.IntegerField()),
                ('file_path', models.FileField(null=True, upload_to='documents/admin_source')),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'la_admin_source',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Build_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('postal_ad_build', models.CharField(max_length=255, null=True)),
                ('house_hold_no', models.CharField(max_length=25, null=True)),
                ('no_floors', models.IntegerField(null=True)),
                ('ext_builduse_type', models.CharField(max_length=100, null=True)),
                ('ext_builduse_sub_type', models.CharField(max_length=100, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roof_type', models.CharField(max_length=20, null=True)),
                ('wall_type', models.CharField(max_length=20, null=True)),
                ('building_name', models.CharField(max_length=255, null=True)),
                ('bld_property_type', models.CharField(max_length=255, null=True)),
                ('registration_date', models.DateField(null=True)),
                ('construction_year', models.IntegerField(null=True)),
                ('structure_type', models.CharField(max_length=30, null=True)),
                ('condition', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'la_ls_build_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_RRR_Audit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rrr_id', models.IntegerField()),
                ('ba_unit_id', models.IntegerField(null=True)),
                ('su_id', models.IntegerField(null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('TERMINATE', 'Terminate'), ('UPDATE', 'Update')], max_length=20)),
                ('changed_by', models.IntegerField()),
                ('changed_by_name', models.CharField(max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField()),
            ],
            options={
                'db_table': 'la_rrr_audit',
                'ordering': ['-changed_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_Spatial_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('su_id', models.IntegerField(unique=True)),
                ('status', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('parcel_status', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'la_spatial_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Last_Active_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('active_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'user_last_active',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtBuildUseSubType_33_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extbuildusesubtype_33',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtBuildUseType_32_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extbuildusetype_32',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtDivisionType_34_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extdivisiontype_34',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtFeatureMainType_35_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extfeaturemaintype_35',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtFeatureMainType_36_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extfeatureytype_36',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtFeatureMainType_37_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extfeaturebuildtype_37',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtLandUseSubType_29_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extlandusesubtype_29',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtLandUseType_28_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extlandusetype_28',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtOuterLegalSpaceUseSubType_31_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extouterlegalspaceusesubtype_31',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtOuterLegalSpaceUseType_30_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extouterlegalspaceusetype_30',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_Int_Providers_39_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_int_providers_39',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_LA_BAUnitType_18_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_la_baunittype_18',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_Org_Names_40_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_org_names_40',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_AdministrativeSourceType_16_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_administrativesourcetype_16',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_AdministrativeStatausType_15_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_administrativestataustype_15',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_AdminRestrictionType_11_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_adminrestrictiontype_11',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_AnnotationType_12_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_annotationtype_12',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_BAUnitType_10_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_baunittype_10',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Education_Level_3_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_education_level_3',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_GenderType_8_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_gendertype_8',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Group_Party_Type_41_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_group_party_type_41',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_HealthStatus_5_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_health_status_5',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_MarriedStatus_6_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_married_status_6',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_Sl_MortgageType_13_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_mortgagetype_13',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Party_Type_1_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lst_sl_party_type_1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_PartyRoleType_2_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_partyroletype_2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Race_4_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_race_4',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Religions_7_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_religions_7',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_ResponsibilityType_17_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_responsibilitytype_17',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_RightShareType_14_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_rightsharetype_14',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_RightType_9_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_righttype_9',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SR_SL_SpatialSourceTypes_27_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sr_sl_spatialsourcetypes_27',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Floor_Type_26_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_floor_type_26',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_LevelContentType_19_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_levelcontenttype_19',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_RegesterType_20_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_regestertype_20',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Roof_Type_24_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_roof_type_24',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Sanitation_23_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_sanitation_23',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_StructureType_21_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_structuretype_21',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Wall_Type_25_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_wall_type_25',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Water_22_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_water_22',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_Tele_Providers_38_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_telecom_providers_38',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Messages_Model',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id_sender', models.IntegerField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('user_id_receiver', models.IntegerField()),
                ('view_status', models.BooleanField(default=False)),
                ('date_viewed', models.DateTimeField(null=True)),
                ('done_status', models.BooleanField(default=False)),
                ('hide_status', models.BooleanField(default=False)),
                ('file_path', models.FileField(null=True, upload_to='documents/message_attachements')),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Org_Area_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org_id', models.IntegerField()),
                ('org_area', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
            options={
                'db_table': 'org_area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Org_Location_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dist', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('org_id', models.IntegerField(unique=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'org_location',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parcel_Delete_Archive_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('su_id', models.IntegerField(db_index=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('parcel_status', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('land_unit_data', models.JSONField(blank=True, null=True)),
                ('assessment_data', models.JSONField(blank=True, null=True)),
                ('tax_info_data', models.JSONField(blank=True, null=True)),
                ('utility_lu_data', models.JSONField(blank=True, null=True)),
                ('zoning_data', models.JSONField(blank=True, null=True)),
                ('physical_env_data', models.JSONField(blank=True, null=True)),
                ('build_unit_data', models.JSONField(blank=True, null=True)),
                ('utility_bu_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parcel_delete_archive',
                'ordering': ['-deleted_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permission_List_Model',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('permission_name', models.CharField(max_length=100)),
                ('view', models.BooleanField(null=True)),
                ('add', models.BooleanField(null=True)),
                ('edit', models.BooleanField(null=True)),
                ('delete', models.BooleanField(null=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'permission_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SL_Department_Model',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=255)),
                ('org_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sl_org_department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SL_Elect_LocalAuth_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gnd_id', models.IntegerField(null=True)),
                ('eletorate', models.CharField(max_length=50, null=True)),
                ('local_auth', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'sl_elect_local_auth',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='sl_gnd_10m_Model',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('gnd', models.CharField(max_length=255)),
                ('dsd', models.CharField(max_length=255)),
                ('dist', models.CharField(max_length=255)),
                ('pd', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'sl_gnd_10m',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SL_Org_Area_Parent_Bndry_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_id', models.IntegerField()),
                ('layer_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('dimension_2d_3d', models.CharField(default='2D', max_length=50)),
                ('reference_coordinate', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'sl_org_area_parent_bndry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SL_Organization_Model',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255, null=True)),
                ('permit_start_date', models.DateField(null=True)),
                ('permit_end_date', models.DateField(null=True)),
                ('org_level', models.IntegerField(default='0')),
                ('director', models.CharField(max_length=100, null=True)),
                ('contact_no', models.CharField(max_length=50, null=True)),
                ('org_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('org_address', models.CharField(max_length=255, null=True)),
                ('subscription_plan', models.CharField(max_length=100, null=True)),
                ('users_limit', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sl_organization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Survey_Rep_Geom_History_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('su_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('layer_id', models.IntegerField()),
                ('calculated_area', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('reference_coordinate', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ref_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'survey_rep_geom_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Survey_Rep_History_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('su_id', models.IntegerField()),
                ('tool', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('user_remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'survey_rep_func_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Test_Data_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
            ],
            options={
                'db_table': 'test_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestJsonModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'test_json',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dep_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='org_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=50),
        ),
        migrations.CreateModel(
            name='LA_LS_Ils_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postal_ad_ils', models.CharField(max_length=255, null=True)),
                ('floor_no', models.IntegerField(null=True)),
                ('house_hold_no', models.CharField(max_length=25, null=True)),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ext_ilsuse_type', models.CharField(max_length=100, null=True)),
                ('ext_ilsuse_sub_type', models.CharField(max_length=100, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roof_type', models.CharField(max_length=20, null=True)),
                ('wall_type', models.CharField(max_length=20, null=True)),
                ('floor_type', models.CharField(max_length=20, null=True)),
                ('ils_name', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ref_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_ls_build_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_ils_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Apt_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postal_ad_apt', models.CharField(max_length=255, null=True)),
                ('floor_no', models.IntegerField(null=True)),
                ('house_hold_no', models.CharField(max_length=25, null=True)),
                ('specific_id', models.CharField(max_length=25, null=True)),
                ('ext_div_type', models.CharField(max_length=100, null=True)),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ext_aptuse_type', models.CharField(max_length=100, null=True)),
                ('ext_aptuse_sub_type', models.CharField(max_length=100, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roof_type', models.CharField(max_length=20, null=True)),
                ('wall_type', models.CharField(max_length=20, null=True)),
                ('floor_type', models.CharField(max_length=20, null=True)),
                ('apt_name', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ref_id', models.OneToOneField(db_column='ref_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_ls_ils_unit_model')),
            ],
            options={
                'db_table': 'la_ls_apt_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Utinet_AU_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water', models.CharField(max_length=15, null=True)),
                ('water_drink', models.CharField(max_length=15, null=True)),
                ('elec', models.CharField(max_length=15, null=True)),
                ('tele', models.CharField(max_length=15, null=True)),
                ('internet', models.CharField(max_length=15, null=True)),
                ('sani_sewer', models.CharField(max_length=50, null=True)),
                ('garbage_dispose', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ref_id', models.OneToOneField(db_column='ref_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_ls_ils_unit_model')),
            ],
            options={
                'db_table': 'la_ls_utinet_au',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Utinet_Ils_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water', models.CharField(max_length=15, null=True)),
                ('water_drink', models.CharField(max_length=15, null=True)),
                ('elec', models.CharField(max_length=15, null=True)),
                ('tele', models.CharField(max_length=15, null=True)),
                ('internet', models.CharField(max_length=15, null=True)),
                ('sani_sewer', models.CharField(max_length=50, null=True)),
                ('garbage_dispose', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ref_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_ls_build_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_utinet_ils',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_RRR_Model',
            fields=[
                ('rrr_id', models.AutoField(primary_key=True, serialize=False)),
                ('rrr_type', models.CharField(max_length=50)),
                ('time_begin', models.DateField(null=True)),
                ('time_end', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('admin_source_id', models.ForeignKey(db_column='admin_source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.la_admin_source_model')),
            ],
            options={
                'db_table': 'la_rrr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_Mortgage_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('interest', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('mortgage_type', models.CharField(max_length=100, null=True)),
                ('mortgage_ref_id', models.CharField(max_length=255, null=True)),
                ('mortgagee', models.CharField(max_length=255, null=True)),
                ('rrr_id', models.OneToOneField(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, related_name='mortgage', to='user.la_rrr_model')),
            ],
            options={
                'db_table': 'la_mortgage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_Spatial_Source_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spatial_source_type', models.CharField(max_length=255, null=True)),
                ('source_id', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('approval_status', models.BooleanField(default=True)),
                ('date_accept', models.DateField(null=True)),
                ('file_path', models.FileField(upload_to='documents/spatial_source')),
                ('surveyor_name', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_spatial_source',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_SP_Fire_Rescue_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_sp_fire_rescue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Zoning_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zoning_category', models.CharField(max_length=10, null=True)),
                ('max_building_height', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('max_coverage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('max_far', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('setback_front', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('setback_rear', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('setback_side', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('special_overlay', models.CharField(max_length=255, null=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_zoning',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Utinet_Ols_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water', models.CharField(max_length=15, null=True)),
                ('water_drink', models.CharField(max_length=15, null=True)),
                ('elec', models.CharField(max_length=15, null=True)),
                ('tele', models.CharField(max_length=15, null=True)),
                ('internet', models.CharField(max_length=15, null=True)),
                ('sani_sewer', models.CharField(max_length=50, null=True)),
                ('sani_gully', models.CharField(max_length=15, null=True)),
                ('drainage', models.CharField(max_length=15, null=True)),
                ('garbage_dispose', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_utinet_ols',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Utinet_LU_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water', models.CharField(max_length=50, null=True)),
                ('elec', models.CharField(max_length=50, null=True)),
                ('drainage', models.CharField(max_length=50, null=True)),
                ('sani_sewer', models.CharField(max_length=50, null=True)),
                ('sani_gully', models.CharField(max_length=50, null=True)),
                ('garbage_dispose', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_utinet_lu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Utinet_BU_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water', models.CharField(max_length=15, null=True)),
                ('water_drink', models.CharField(max_length=15, null=True)),
                ('elec', models.CharField(max_length=15, null=True)),
                ('tele', models.CharField(max_length=15, null=True)),
                ('internet', models.CharField(max_length=15, null=True)),
                ('sani_sewer', models.CharField(max_length=50, null=True)),
                ('sani_gully', models.CharField(max_length=50, null=True)),
                ('garbage_dispose', models.CharField(max_length=15, null=True)),
                ('drainage', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_utinet_bu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Physical_Env_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elevation', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('slope', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('soil_type', models.CharField(max_length=20, null=True)),
                ('flood_zone', models.BooleanField(null=True)),
                ('vegetation_cover', models.CharField(max_length=255, null=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_physical_env',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Ols_Polygon_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('postal_ad_ols', models.CharField(max_length=255, null=True)),
                ('ols_main_type', models.CharField(max_length=100, null=True)),
                ('ext_olsuse_type', models.CharField(max_length=100, null=True)),
                ('ext_olsuse_sub_type', models.CharField(max_length=100, null=True)),
                ('ols_x_type', models.CharField(max_length=100, null=True)),
                ('ols_build_type', models.CharField(max_length=100, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ols_poly_name', models.CharField(max_length=255, null=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_ols_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Ols_PointLine_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('ols_made_type', models.CharField(max_length=100, null=True)),
                ('ols_main_type', models.CharField(max_length=100, null=True)),
                ('ols_x_type', models.CharField(max_length=100, null=True)),
                ('ols_build_type', models.CharField(max_length=100, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ols_point_line_name', models.CharField(max_length=255, null=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_ols_pointline_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_MyLayer_Polygon_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('postal_ad_ols', models.CharField(max_length=255, null=True)),
                ('ols_main_type', models.CharField(max_length=100, null=True)),
                ('ext_olsuse_type', models.CharField(max_length=100, null=True)),
                ('ext_olsuse_sub_type', models.CharField(max_length=100, null=True)),
                ('ols_x_type', models.CharField(max_length=100, null=True)),
                ('ols_build_type', models.CharField(max_length=100, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_mylayer_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_MyLayer_PointLine_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('ols_made_type', models.CharField(max_length=100, null=True)),
                ('ols_main_type', models.CharField(max_length=100, null=True)),
                ('ols_x_type', models.CharField(max_length=100, null=True)),
                ('ols_build_type', models.CharField(max_length=100, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_mylayer_pointline_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Land_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('postal_ad_lnd', models.CharField(max_length=255, null=True)),
                ('local_auth', models.CharField(blank=True, max_length=255, null=True)),
                ('ext_landuse_type', models.CharField(max_length=100, null=True)),
                ('ext_landuse_sub_type', models.CharField(max_length=100, null=True)),
                ('sl_land_type', models.CharField(max_length=30, null=True)),
                ('land_name', models.CharField(max_length=255, null=True)),
                ('registration_date', models.DateField(null=True)),
                ('tenure_type', models.CharField(max_length=30, null=True)),
                ('adjacent_parcels', models.CharField(max_length=500, null=True)),
                ('parent_parcel', models.CharField(max_length=100, null=True)),
                ('child_parcels', models.CharField(max_length=500, null=True)),
                ('part_of_estate', models.CharField(max_length=255, null=True)),
                ('area', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('perimeter', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('dimension_2d_3d', models.CharField(max_length=3, null=True)),
                ('boundary_type', models.CharField(max_length=30, null=True)),
                ('crs', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_land_unit',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='la_ls_build_unit_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.CreateModel(
            name='Inquiries_Model',
            fields=[
                ('inq_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id_creator', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('inquiry_type', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('user_id_assigned', models.IntegerField()),
                ('view_status', models.BooleanField(default=False)),
                ('date_viewed', models.DateTimeField(null=True)),
                ('done_status', models.BooleanField(default=False)),
                ('hide_status', models.BooleanField(default=False)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'Inquiries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='History_Spartialunit_Attrib_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('su_id', models.ForeignKey(db_column='su_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'history_spatialunit_attrib',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Attrib_Image_Model',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file_path', models.FileField(null=True, upload_to='documents/images')),
                ('status', models.BooleanField(default=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'attrib_panel_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assessment_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_ass_id', models.CharField(max_length=255, null=True)),
                ('assessment_no', models.CharField(max_length=20, null=True)),
                ('ass_road', models.CharField(max_length=255, null=True)),
                ('assessment_annual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('assessment_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_of_valuation', models.DateField(null=True)),
                ('year_of_assessment', models.CharField(max_length=4, null=True)),
                ('property_type', models.CharField(max_length=255, null=True)),
                ('assessment_name', models.CharField(max_length=255, null=True)),
                ('ass_out_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('land_value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tax_status', models.CharField(max_length=10, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'assessment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LayersModel',
            fields=[
                ('layer_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('layer_name', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('group_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('org_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'layers',
                'unique_together': {('user_id', 'layer_name')},
            },
        ),
        migrations.CreateModel(
            name='LA_Level_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(db_column='content_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.lst_su_sl_levelcontenttype_19_model')),
                ('register_type', models.ForeignKey(db_column='register_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.lst_su_sl_regestertype_20_model')),
                ('structure_type', models.ForeignKey(db_column='structure_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.lst_su_sl_structuretype_21_model')),
            ],
            options={
                'db_table': 'la_level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Party_Model',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=255)),
                ('party_full_name', models.CharField(max_length=255)),
                ('la_party_type', models.CharField(max_length=255, null=True)),
                ('sl_party_type', models.CharField(max_length=255, null=True)),
                ('ext_pid_type', models.CharField(max_length=255, null=True)),
                ('ext_pid', models.CharField(max_length=255, null=True)),
                ('pmt_address', models.CharField(max_length=255, null=True)),
                ('tp', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), null=True, size=None)),
                ('specific_tp', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('other_reg', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('remark', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.IntegerField()),
            ],
            options={
                'db_table': 'sl_party',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('ext_pid_type', 'ext_pid'), name='unique_ext_pid_type_pid'), models.UniqueConstraint(fields=('sl_party_type', 'specific_tp'), name='unique_sl_party_type_specific_tp')],
            },
        ),
        migrations.CreateModel(
            name='LA_Spatial_Unit_Sketch_Ref_Model',
            fields=[
                ('sketch_ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('sketch_ref_type', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('approval_status', models.BooleanField(default=True)),
                ('avl_status', models.BooleanField(default=True)),
                ('file_path', models.FileField(null=True, upload_to='documents/sketch_ref')),
                ('status', models.BooleanField(default=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
                ('doc_owner', models.ForeignKey(db_column='doc_owner', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
            ],
            options={
                'db_table': 'la_spatial_unit_sketch_ref',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Party_Roles_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_role_type', models.CharField(max_length=255)),
                ('share_type', models.CharField(blank=True, max_length=100, null=True)),
                ('share', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.IntegerField()),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
                ('rrr_id', models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model')),
            ],
            options={
                'db_table': 'sl_party_roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reminders_Model',
            fields=[
                ('rmd_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id_creator', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reminder_type', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('date_remind', models.DateTimeField()),
                ('done_status', models.BooleanField(default=False)),
                ('hide_status', models.BooleanField(default=False)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'reminders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Residence_Info_Model',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('resident_type', models.CharField(max_length=50)),
                ('user_added_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
                ('su_id', models.ForeignKey(db_column='su_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'residence_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SL_BA_Unit_Model',
            fields=[
                ('ba_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('sl_ba_unit_type', models.CharField(max_length=30)),
                ('sl_ba_unit_name', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.PROTECT, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'sl_ba_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_RRR_Restriction_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rrr_restriction_type', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('time_begin', models.DateField(null=True)),
                ('time_end', models.DateField(null=True)),
                ('ba_unit_id', models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.PROTECT, related_name='restrictions', to='user.sl_ba_unit_model')),
            ],
            options={
                'db_table': 'la_rrr_restriction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_RRR_Responsibility_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rrr_responsibility_type', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('time_begin', models.DateField(null=True)),
                ('time_end', models.DateField(null=True)),
                ('ba_unit_id', models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.PROTECT, related_name='responsibilities', to='user.sl_ba_unit_model')),
            ],
            options={
                'db_table': 'la_rrr_responsibility',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='la_rrr_model',
            name='ba_unit_id',
            field=models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.PROTECT, to='user.sl_ba_unit_model'),
        ),
        migrations.CreateModel(
            name='LA_RRR_Document_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_source', models.ForeignKey(db_column='admin_source_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_admin_source_model')),
                ('ba_unit', models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model')),
            ],
            options={
                'db_table': 'la_rrr_document',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SL_Org_Area_Child_Bndry_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_id', models.IntegerField()),
                ('layer_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('dimension_2d_3d', models.CharField(default='2D', max_length=50)),
                ('reference_coordinate', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('parent_id', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_org_area_parent_bndry_model')),
            ],
            options={
                'db_table': 'sl_org_area_child_bndry',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='sl_org_area_parent_bndry_model',
            name='org_id',
            field=models.OneToOneField(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_organization_model'),
        ),
        migrations.CreateModel(
            name='Survey_Rep_DATA_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_id', models.IntegerField()),
                ('layer_id', models.IntegerField(db_index=True)),
                ('geom_type', models.CharField(max_length=255)),
                ('calculated_area', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('legal_area', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('legal_area_unit', models.CharField(choices=[('sqm', 'sq.m'), ('acres', 'Acres'), ('perches', 'Perches')], max_length=20, null=True)),
                ('dimension_2d_3d', models.CharField(default='2D', max_length=50)),
                ('reference_coordinate', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('status', models.BooleanField(default=True)),
                ('parent_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('ref_id', models.IntegerField(db_column='ref_ids', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('gnd_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('org_id', models.IntegerField(db_index=True, null=True)),
                ('su_id', models.ForeignKey(db_column='su_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'survey_rep',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tags_Model',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id_creator', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tag_type', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('deleted_user', models.CharField(max_length=255, null=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tax_Info_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_annual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_valuation', models.DateTimeField(null=True)),
                ('tax_date', models.DateField(null=True)),
                ('tax_type', models.CharField(max_length=255, null=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'tax_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Test_List_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_id', models.IntegerField()),
                ('permission_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, null=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('party_id', models.ForeignKey(db_column='my_party_id', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
            ],
            options={
                'db_table': 'test_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Roles_Model',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('admin_id', models.IntegerField()),
                ('org_id', models.IntegerField(db_index=True)),
                ('role_type', models.CharField(default='user', max_length=20)),
            ],
            options={
                'db_table': 'user_roles',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('role_name', 'org_id'), name='roles_for_org')],
            },
        ),
        migrations.CreateModel(
            name='LA_BAUnit_SpatialUnit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(default='PRIMARY', max_length=20, null=True)),
                ('su', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
                ('ba_unit', models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model')),
            ],
            options={
                'db_table': 'la_ba_unit_spatial_unit',
                'managed': True,
                'unique_together': {('ba_unit', 'su')},
            },
        ),
        migrations.CreateModel(
            name='Role_Permission_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('view', models.BooleanField(null=True)),
                ('add', models.BooleanField(null=True)),
                ('edit', models.BooleanField(null=True)),
                ('delete', models.BooleanField(null=True)),
                ('permission_id', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='user.permission_list_model')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='user.user_roles_model')),
            ],
            options={
                'db_table': 'role_permission',
                'managed': True,
                'indexes': [models.Index(fields=['role_id', 'permission_id'], name='idx_roleperm_role_perm')],
            },
        ),
    ]
