# Generated by Django 5.1 on 2026-04-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_create_parcel_archive_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_ls_physical_env_model',
            name='flood_zone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='la_ls_zoning_model',
            name='zoning_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
