# Generated by Django 5.1 on 2024-10-01 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_address_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayersModel',
            fields=[
                ('layer_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_id', models.CharField(max_length=255)),
                ('layer_name', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=255, null=True)),
                ('order_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'layers',
                'unique_together': {('user_id', 'layer_name')},
            },
        ),
    ]
