# Generated by Django 5.1 on 2026-05-11 13:20
#
# Performance + schema cleanup pass:
#   1. Drop the leftover `ladm_anti_conflict` trigger on `survey_rep` whose
#      body is just `pg_sleep(3)` — it caused every INSERT/UPDATE on
#      survey_rep to stall 3 seconds (polygon save was 6+ s).
#   2. Rename two columns on `sl_gnd_10m` that were imported with hidden
#      trailing whitespace (`"gid\u00a0"` and `"geom\u00a0"` in one dump), so the Django models can
#      reference them by their clean names.
#   3. Drop the duplicate GiST index on geom.
#
# Both blocks are idempotent (DROP IF EXISTS / column-name guard), so this
# is safe on databases where the fixes were already applied manually.

from django.db import migrations


FIX_GND_COLUMN_SPACES = """
DROP INDEX IF EXISTS sl_gnd_10m_geom_gist;

DO $$
DECLARE
    bad_gid_name  text;
    bad_geom_name text;
BEGIN
    SELECT column_name INTO bad_gid_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'sl_gnd_10m'
      AND column_name LIKE 'gid%'
      AND column_name <> 'gid'
    ORDER BY ordinal_position
    LIMIT 1;

    SELECT column_name INTO bad_geom_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'sl_gnd_10m'
      AND column_name LIKE 'geom%'
      AND column_name <> 'geom'
    ORDER BY ordinal_position
    LIMIT 1;

    IF bad_geom_name IS NOT NULL
       AND EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = 'public'
             AND table_name = 'sl_gnd_10m'
             AND column_name = 'geom'
       ) THEN
        ALTER TABLE sl_gnd_10m DROP COLUMN geom;
        RAISE NOTICE 'Dropped duplicate clean geom column before rename';
    END IF;

    IF bad_gid_name IS NOT NULL
       AND EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = 'public'
             AND table_name = 'sl_gnd_10m'
             AND column_name = 'gid'
       ) THEN
        ALTER TABLE sl_gnd_10m DROP COLUMN gid;
        RAISE NOTICE 'Dropped duplicate clean gid column before rename';
    END IF;

    IF bad_gid_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE sl_gnd_10m RENAME COLUMN %I TO gid', bad_gid_name);
        RAISE NOTICE 'Renamed gid column from hex %',
            encode(convert_to(bad_gid_name, 'UTF8'), 'hex');
    END IF;

    IF bad_geom_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE sl_gnd_10m RENAME COLUMN %I TO geom', bad_geom_name);
        RAISE NOTICE 'Renamed geom column from hex %',
            encode(convert_to(bad_geom_name, 'UTF8'), 'hex');
    END IF;
END$$;

ANALYZE sl_gnd_10m;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_add_apt_fields_to_build_unit"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "DROP TRIGGER IF EXISTS ladm_trigger ON survey_rep;",
                "DROP FUNCTION IF EXISTS ladm_anti_conflict();",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=FIX_GND_COLUMN_SPACES,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
