# Generated by Codex on 2026-05-11
#
# Some sl_gnd_10m imports create columns named "gid\u00a0" and "geom\u00a0" with a
# trailing non-breaking space. The earlier cleanup migration only looked for
# ASCII spaces, so databases that already marked that migration as applied need
# this idempotent follow-up.

from django.db import migrations


NORMALIZE_GND_HIDDEN_WHITESPACE = """
DO $$
DECLARE
    bad_gid_name  text;
    bad_geom_name text;
BEGIN
    SELECT column_name INTO bad_gid_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'sl_gnd_10m'
      AND column_name LIKE 'gid%'
      AND column_name <> 'gid'
    ORDER BY ordinal_position
    LIMIT 1;

    SELECT column_name INTO bad_geom_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'sl_gnd_10m'
      AND column_name LIKE 'geom%'
      AND column_name <> 'geom'
    ORDER BY ordinal_position
    LIMIT 1;

    IF bad_geom_name IS NOT NULL
       AND EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = 'public'
             AND table_name = 'sl_gnd_10m'
             AND column_name = 'geom'
       ) THEN
        ALTER TABLE sl_gnd_10m DROP COLUMN geom;
        RAISE NOTICE 'Dropped duplicate clean geom column before rename';
    END IF;

    IF bad_gid_name IS NOT NULL
       AND EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = 'public'
             AND table_name = 'sl_gnd_10m'
             AND column_name = 'gid'
       ) THEN
        ALTER TABLE sl_gnd_10m DROP COLUMN gid;
        RAISE NOTICE 'Dropped duplicate clean gid column before rename';
    END IF;

    IF bad_gid_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE sl_gnd_10m RENAME COLUMN %I TO gid', bad_gid_name);
        RAISE NOTICE 'Renamed gid column from hex %',
            encode(convert_to(bad_gid_name, 'UTF8'), 'hex');
    END IF;

    IF bad_geom_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE sl_gnd_10m RENAME COLUMN %I TO geom', bad_geom_name);
        RAISE NOTICE 'Renamed geom column from hex %',
            encode(convert_to(bad_geom_name, 'UTF8'), 'hex');
    END IF;
END$$;

ANALYZE sl_gnd_10m;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_drop_ladm_anti_conflict_trigger"),
    ]

    operations = [
        migrations.RunSQL(
            sql=NORMALIZE_GND_HIDDEN_WHITESPACE,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
