# Generated by Django 5.1 on 2024-10-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_birthday_user_nic_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='n/a', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1976-01-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='0770000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='nic',
            field=models.CharField(default='000000000000', max_length=20),
        ),
    ]
