# Generated by Django 5.1 on 2024-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
