# Generated by Codex on 2026-05-17
#
# Some restored databases still contain the GND geometry column as "geom\xa0"
# (non-breaking trailing space). Earlier migrations tried to rename it, but a
# later restore can leave the migration marked applied while the live schema is
# still dirty. This migration is intentionally idempotent and preserves geometry
# values when a duplicate clean geom column already exists.

from django.db import migrations


NORMALIZE_GND_GEOM_COLUMN = """
DO $$
DECLARE
    bad_geom_name text;
BEGIN
    SELECT column_name INTO bad_geom_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'sl_gnd_10m'
      AND column_name <> 'geom'
      AND column_name <> 'geom_ladm'
      AND regexp_replace(column_name, '[[:space:]\\u00A0]+$', '', 'g') = 'geom'
    ORDER BY ordinal_position
    LIMIT 1;

    IF bad_geom_name IS NULL THEN
        RETURN;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'sl_gnd_10m'
          AND column_name = 'geom'
    ) THEN
        EXECUTE format(
            'UPDATE sl_gnd_10m SET geom = COALESCE(geom, %I) WHERE geom IS NULL',
            bad_geom_name
        );
        EXECUTE format('ALTER TABLE sl_gnd_10m DROP COLUMN %I', bad_geom_name);
        RAISE NOTICE 'Copied and dropped bad GND geom column from hex %',
            encode(convert_to(bad_geom_name, 'UTF8'), 'hex');
    ELSE
        EXECUTE format('ALTER TABLE sl_gnd_10m RENAME COLUMN %I TO geom', bad_geom_name);
        RAISE NOTICE 'Renamed bad GND geom column from hex %',
            encode(convert_to(bad_geom_name, 'UTF8'), 'hex');
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS sl_gnd_10m_geom_gist ON sl_gnd_10m USING GIST (geom);
ANALYZE sl_gnd_10m;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_create_parcel_history"),
    ]

    operations = [
        migrations.RunSQL(
            sql=NORMALIZE_GND_GEOM_COLUMN,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
