# Generated by Django 5.1 on 2024-10-10 06:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_department_user_organization_user_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_VectorDATA_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('dataset_name', models.CharField(max_length=255)),
                ('layer_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=4326)),
            ],
            options={
                'db_table': 'import_vector_data',
                'managed': True,
            },
        ),
    ]
