# Generated by Codex on 2026-05-18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_normalize_gnd_geom_column_again"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcel_Event_Model",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("primary_su_id", models.IntegerField(db_index=True)),
                ("event_type", models.CharField(db_index=True, max_length=40)),
                ("summary", models.TextField()),
                ("status", models.CharField(db_index=True, default="active", max_length=30)),
                (
                    "affected_parcel_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, null=True, size=None
                    ),
                ),
                ("source_history_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("source_event_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("before_snapshot", models.JSONField(blank=True, null=True)),
                ("after_snapshot", models.JSONField(blank=True, null=True)),
                ("rectification_reason", models.TextField(blank=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_by_name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("rectified_by", models.IntegerField(blank=True, null=True)),
                ("rectified_at", models.DateTimeField(blank=True, null=True)),
                ("can_rectify", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "parcel_event",
                "ordering": ["-created_at", "-id"],
                "managed": True,
            },
        ),
    ]
