# Generated by Django 5.1 on 2024-10-23 12:50

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_import_vectordata_model_dataset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='survey_rep_DATA_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_id', models.CharField(max_length=255)),
                ('layer_id', models.IntegerField()),
                ('infobhoomi_id', models.CharField(max_length=255, null=True)),
                ('geom_type', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('dimension_2d_3d', models.CharField(max_length=50, null=True)),
                ('reference_coordinate', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('geom_level', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=10)),
                ('parent_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('reference_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'survey_rep',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='survey_rep_history_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('su_id', models.IntegerField()),
                ('tool', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=255)),
                ('user_remark', models.TextField()),
            ],
            options={
                'db_table': 'survey_rep_history',
                'managed': True,
            },
        ),
    ]
