# Generated by Django 5.1 on 2024-10-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_survey_rep_data_model_survey_rep_history_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_history_model',
            name='user_remark',
            field=models.TextField(null=True),
        ),
    ]
