# Generated by Django 5.1 on 2024-10-28 10:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_layersmodel_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layersmodel',
            name='group_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default='1', null=True, size=None),
        ),
    ]
