# Generated by Django 5.1 on 2024-10-30 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_layersmodel_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission_List_Model',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'permission_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Roles_Model',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('admin_id', models.CharField(max_length=50)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_roles',
                'managed': True,
            },
        ),
    ]
