# Generated by Django 5.1 on 2024-10-31 02:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_permission_list_model_user_roles_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Data_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None, unique=True)),
            ],
            options={
                'db_table': 'test_data',
                'managed': True,
            },
        ),
    ]
