# Generated by Django 5.1 on 2024-10-31 02:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_test_data_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_data_model',
            name='note',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
    ]
