# Generated by Django 5.1 on 2024-10-31 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_test_data_model_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_data_model',
            old_name='note',
            new_name='users',
        ),
    ]
