# Generated by Django 5.1 on 2026-08-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_backfill_3d_perms_super_admin_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Activity_Log_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id_creator', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(db_index=True, max_length=50)),
                ('content', models.TextField(null=True)),
                ('su_id', models.ForeignKey(blank=True, db_column='su_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'user_activity_log',
                'managed': True,
            },
        ),
    ]
