# Generated by Django 5.1 on 2024-10-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_rename_note_test_data_model_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles_model',
            name='role_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
