# Generated by Django 5.1 on 2024-10-31 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_user_roles_model_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_Permission_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('view', models.BooleanField(default=True)),
                ('edit', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('date_view', models.DateTimeField(null=True)),
                ('date_edit', models.DateTimeField(null=True)),
                ('date_delete', models.DateTimeField(null=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('permission_id', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='user.permission_list_model')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='user.user_roles_model')),
            ],
            options={
                'db_table': 'role_permission',
                'managed': True,
            },
        ),
    ]
