# Generated by Django 5.1 on 2024-11-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_role_permission_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_List_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_id', models.IntegerField()),
                ('permission_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, null=True)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'test_list',
                'managed': True,
            },
        ),
    ]
