# Generated by Django 5.1 on 2024-11-03 06:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_test_list_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_vectordata_model',
            name='raster',
            field=django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='import_vectordata_model',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
