# Generated by Django 5.1 on 2024-11-03 07:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_import_vectordata_model_raster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_RasterDATA_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('dataset_name', models.CharField(max_length=255, unique=True)),
                ('layer_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'import_raster_data',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='import_vectordata_model',
            name='raster',
        ),
    ]
