# Generated by Django 5.1 on 2024-11-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_import_rasterdata_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Import_RasterDATA_Model',
        ),
    ]
