# Generated by Django 5.1 on 2024-11-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_delete_import_rasterdata_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layersmodel',
            unique_together=set(),
        ),
    ]
