# Generated by Django 5.1 on 2024-11-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_layersmodel_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layersmodel',
            old_name='user_id',
            new_name='username',
        ),
    ]
