# Generated by Django 5.1 on 2024-11-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_rename_user_id_layersmodel_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layersmodel',
            unique_together={('username', 'layer_name')},
        ),
    ]
