# Generated by Django 5.1 on 2024-11-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_layersmodel_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_roles_model',
            old_name='admin_id',
            new_name='admin_name',
        ),
    ]
