# Generated by Django 5.1 on 2024-11-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_rename_admin_id_user_roles_model_admin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey_rep_history_model',
            old_name='user_id',
            new_name='username',
        ),
    ]
