# Generated by Django 5.1 on 2024-11-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_rename_user_id_survey_rep_history_model_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='import_vectordata_model',
            old_name='user_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='survey_rep_data_model',
            old_name='user_id',
            new_name='username',
        ),
    ]
