# Generated by Django 5.1 on 2024-11-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_rename_user_id_import_vectordata_model_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_permission_model',
            name='add',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role_permission_model',
            name='date_add',
            field=models.DateTimeField(null=True),
        ),
    ]
