# Generated by Django 5.1 on 2024-11-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_role_permission_model_add_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role_Permission_Model',
        ),
    ]
