# Generated by Django 5.1 on 2024-11-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_role_permission_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_permission_model',
            name='permission_id',
        ),
    ]
