# Generated by Django 5.1 on 2024-11-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_remove_role_permission_model_permission_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role_Permission_Model',
        ),
    ]
