# Generated by Django 5.1 on 2024-11-11 12:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_role_permission_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party_Model',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=255)),
                ('la_party_type', models.CharField(max_length=255, null=True)),
                ('sl_party_type', models.CharField(max_length=255, null=True)),
                ('ext_pid_type', models.CharField(max_length=255, null=True)),
                ('ext_pid', models.CharField(max_length=255, null=True)),
                ('ref_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('pmt_address', models.CharField(max_length=255, null=True)),
                ('tp', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), null=True, size=None)),
                ('specific_tp', models.CharField(max_length=10, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('edu', models.CharField(max_length=20, null=True)),
                ('religion', models.CharField(max_length=15, null=True)),
                ('race', models.CharField(max_length=15, null=True)),
                ('married_status', models.CharField(max_length=15, null=True)),
                ('health_status', models.CharField(max_length=50, null=True)),
                ('other_reg', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'sl_party',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('ext_pid_type', 'ext_pid'), name='unique_ext_pid_type_pid')],
            },
        ),
    ]
