# Generated by Django 5.1 on 2024-11-13 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_party_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence_Info_Model',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('su_id', models.IntegerField()),
                ('resident_type', models.CharField(max_length=50)),
                ('user_added_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
            ],
            options={
                'db_table': 'residence_info',
                'managed': True,
            },
        ),
    ]
