# Generated by Django 5.1 on 2024-11-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_sl_rights_liabilities_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SL_Rights_Liabilities_Model',
        ),
    ]
