# Generated by Django 5.1 on 2024-11-13 08:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_delete_sl_rights_liabilities_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SL_Rights_Liabilities_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='sl_rl', max_length=10)),
                ('su_id', models.IntegerField()),
                ('sl_right_type', models.CharField(max_length=50, null=True)),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(null=True)),
                ('sl_rl_parties', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
            ],
        ),
    ]
