# Generated by Django 5.1 on 2024-11-13 09:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_sl_rights_liabilities_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Annotation_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='a_a', max_length=10)),
                ('su_id', models.IntegerField()),
                ('admin_anno_type', models.CharField(max_length=50, null=True)),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('a_a_parties', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('admin_source_type', models.CharField(max_length=50, null=True)),
                ('admin_source_id', models.IntegerField(null=True)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('claiment_pid', models.ForeignKey(db_column='claiment_pid', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
            ],
            options={
                'db_table': 'admin_annotation',
                'managed': True,
            },
        ),
    ]
