# Generated by Django 5.1 on 2024-11-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_admin_annotation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_annotation_model',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sl_rights_liabilities_model',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
