# Generated by Django 5.1 on 2024-11-13 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_admin_annotation_model_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SL_Admin_Restrict_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='sl_ad_res', max_length=10)),
                ('su_id', models.IntegerField()),
                ('sl_adm_res_type', models.CharField(max_length=50, null=True)),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('adm_res_legal_space', models.CharField(max_length=50, null=True)),
                ('adm_res_legal_prov', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('gov_party', models.ForeignKey(db_column='gov_party', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
            ],
            options={
                'db_table': 'sl_admin_restrict',
                'managed': True,
            },
        ),
    ]
