# Generated by Django 5.1 on 2024-11-13 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_sl_admin_restrict_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_Mortgage_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='la_mort', max_length=10)),
                ('su_id', models.IntegerField()),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('int_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('sl_mortgage_type', models.CharField(max_length=50, null=True)),
                ('mort_id', models.IntegerField(null=True)),
                ('mortgagee', models.IntegerField(null=True)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('mortgagor', models.ForeignKey(db_column='mortgagor', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
            ],
            options={
                'db_table': 'la_Mortgage',
                'managed': True,
            },
        ),
    ]
