# Generated by Django 5.1 on 2024-11-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_la_mortgage_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SL_Rights_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='sl_right', max_length=10)),
                ('su_id', models.IntegerField()),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('right_type', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('right_party', models.ForeignKey(db_column='right_party', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
            ],
            options={
                'db_table': 'sl_rights',
                'managed': True,
            },
        ),
    ]
