# Generated by Django 5.1 on 2024-11-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_sl_rights_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_Responsibility_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='la_responsibility', max_length=20)),
                ('su_id', models.IntegerField()),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('responsibility_type', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('responsibility_party', models.ForeignKey(db_column='responsibility_party', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
            ],
            options={
                'db_table': 'la_responsibility',
                'managed': True,
            },
        ),
    ]
