# Generated by Django 5.1 on 2024-11-14 08:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_la_responsibility_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_RRR_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('su_id', models.IntegerField()),
                ('code', models.CharField(max_length=20)),
                ('code_id', models.IntegerField()),
                ('rrr_id', models.IntegerField()),
                ('admin_source_id', models.IntegerField(null=True)),
                ('ba_unit_id', models.IntegerField()),
                ('ba_unit_type', models.CharField(max_length=20, null=True)),
                ('pid_share_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'la_rrr',
                'managed': True,
            },
        ),
    ]
