# Generated by Django 5.1 on 2024-11-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_la_admin_source_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_annotation_model',
            name='admin_source_id',
        ),
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='admin_source_id',
        ),
    ]
