# Generated by Django 5.1 on 2024-11-14 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_remove_admin_annotation_model_admin_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_annotation_model',
            name='admin_source_id',
            field=models.ForeignKey(db_column='admin_source_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.la_admin_source_model'),
        ),
        migrations.AddField(
            model_name='la_rrr_model',
            name='admin_source_id',
            field=models.ForeignKey(db_column='admin_source_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.la_admin_source_model'),
        ),
    ]
