# Generated by Django 5.1 on 2024-11-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_admin_annotation_model_admin_source_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='admin_source_id',
        ),
        migrations.RemoveField(
            model_name='admin_annotation_model',
            name='admin_source_id',
        ),
        migrations.DeleteModel(
            name='LA_Admin_Source_Model',
        ),
    ]
