# Generated by Django 5.1 on 2024-11-14 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_remove_la_rrr_model_admin_source_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_Admin_Source_Model',
            fields=[
                ('admin_source_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('admin_source_type', models.CharField(max_length=255, null=True)),
                ('su_id', models.IntegerField()),
                ('reference_no', models.CharField(max_length=255, null=True)),
                ('acceptance_date', models.DateTimeField()),
                ('exte_arch_ref', models.CharField(max_length=255, null=True)),
                ('life_span_stamp', models.CharField(max_length=255, null=True)),
                ('approval_status', models.BooleanField(default=True)),
                ('avl_status', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('file_path', models.FileField(null=True, upload_to='documents/admin_source')),
                ('status', models.BooleanField(default=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modifydate_exte_arch_ref', models.DateTimeField(null=True)),
                ('modifydate_life_span_stamp', models.DateTimeField(null=True)),
                ('modifydate_acceptance_date', models.DateTimeField(null=True)),
                ('modifydate_reference_no', models.DateTimeField(null=True)),
                ('doc_owner', models.ForeignKey(db_column='doc_owner', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
            ],
            options={
                'db_table': 'la_admin_source',
                'managed': True,
            },
        ),
    ]
