# Generated by Django 5.1 on 2024-11-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_admin_annotation_model_admin_source_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SL_BA_Unit_Model',
            fields=[
                ('ba_unit_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('su_id', models.IntegerField()),
                ('ba_unit_type', models.CharField(max_length=30, null=True)),
                ('ba_unit_name', models.CharField(max_length=255, null=True)),
                ('pd', models.CharField(max_length=50, null=True)),
                ('dist', models.CharField(max_length=50, null=True)),
                ('dsd', models.CharField(max_length=50, null=True)),
                ('gnd', models.CharField(max_length=50, null=True)),
                ('eletorate', models.CharField(max_length=50, null=True)),
                ('local_auth', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'sl_ba_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_Spatial_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('su_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('reference_id', models.IntegerField(null=True)),
                ('ladm_value', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=255, null=True)),
                ('util_obj_id', models.IntegerField(null=True)),
                ('util_obj_code', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'la_spatial_unit',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('util_obj_id', 'util_obj_code'), name='util_obj_id_util_obj_code')],
            },
        ),
    ]
