# Generated by Django 5.1 on 2024-11-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_sl_ba_unit_model_la_spatial_unit_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_Spatial_Unit_Ref_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('su_id', models.IntegerField()),
                ('reference_id', models.IntegerField()),
            ],
            options={
                'db_table': 'la_spatial_unit_ref',
                'managed': True,
            },
        ),
    ]
