# Generated by Django 5.1 on 2024-11-14 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_alter_la_spatial_unit_model_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_spatial_unit_model',
            name='reference_id',
            field=models.ForeignKey(db_column='reference_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_ref_model'),
        ),
        migrations.AlterField(
            model_name='la_spatial_unit_model',
            name='su_id',
            field=models.IntegerField(unique=True),
        ),
    ]
