# Generated by Django 5.1 on 2024-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_alter_la_spatial_unit_model_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_spatial_unit_model',
            name='reference_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='LA_Spatial_Unit_Ref_Model',
        ),
    ]
