# Generated by Django 5.1 on 2024-11-16 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_alter_la_spatial_unit_model_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_rrr_model',
            name='ba_unit_id',
            field=models.ForeignKey(db_column='ba_unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model'),
        ),
    ]
