# Generated by Django 5.1 on 2024-11-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_alter_la_rrr_model_ba_unit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_annotation_model',
            old_name='su_id',
            new_name='ba_unit_id',
        ),
        migrations.RenameField(
            model_name='la_mortgage_model',
            old_name='su_id',
            new_name='ba_unit_id',
        ),
        migrations.RenameField(
            model_name='la_responsibility_model',
            old_name='su_id',
            new_name='ba_unit_id',
        ),
        migrations.RenameField(
            model_name='sl_admin_restrict_model',
            old_name='su_id',
            new_name='ba_unit_id',
        ),
        migrations.RenameField(
            model_name='sl_rights_liabilities_model',
            old_name='su_id',
            new_name='ba_unit_id',
        ),
        migrations.RenameField(
            model_name='sl_rights_model',
            old_name='su_id',
            new_name='ba_unit_id',
        ),
        migrations.AddConstraint(
            model_name='la_rrr_model',
            constraint=models.UniqueConstraint(fields=('code', 'code_id'), name='code_code_id'),
        ),
    ]
