# Generated by Django 5.1 on 2024-11-16 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_rename_su_id_admin_annotation_model_ba_unit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_annotation_model',
            name='ba_unit_id',
            field=models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model'),
        ),
        migrations.AlterField(
            model_name='la_mortgage_model',
            name='ba_unit_id',
            field=models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model'),
        ),
        migrations.AlterField(
            model_name='la_responsibility_model',
            name='ba_unit_id',
            field=models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model'),
        ),
        migrations.AlterField(
            model_name='sl_admin_restrict_model',
            name='ba_unit_id',
            field=models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model'),
        ),
        migrations.AlterField(
            model_name='sl_rights_liabilities_model',
            name='ba_unit_id',
            field=models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model'),
        ),
        migrations.AlterField(
            model_name='sl_rights_model',
            name='ba_unit_id',
            field=models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model'),
        ),
    ]
