# Generated by Django 5.1 on 2024-11-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_alter_sl_ba_unit_model_su_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey_rep_data_model',
            name='geom_level',
        ),
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='dimension_2d_3d',
            field=models.CharField(default='2D', max_length=50),
        ),
    ]
