# Generated by Django 5.1 on 2024-11-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_remove_survey_rep_data_model_geom_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
