# Generated by Django 5.1 on 2024-11-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_alter_survey_rep_data_model_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey_rep_data_model',
            name='status',
        ),
    ]
