# Generated by Django 5.1 on 2024-11-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_remove_survey_rep_data_model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
