# Generated by Django 5.1 on 2024-11-16 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_remove_survey_rep_data_model_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_spatial_unit_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.survey_rep_data_model'),
        ),
    ]
