# Generated by Django 5.1 on 2024-11-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_alter_la_spatial_unit_model_su_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_admin_source_model',
            name='admin_source_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='la_spatial_unit_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sl_ba_unit_model',
            name='ba_unit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LA_LS_Land_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('postal_ad_lnd', models.CharField(max_length=255, null=True)),
                ('ext_landuse_type', models.CharField(max_length=100, null=True)),
                ('ext_landuse_sub_type', models.CharField(max_length=100, null=True)),
                ('sl_land_type', models.CharField(max_length=30, null=True)),
                ('file_path', models.FileField(null=True, upload_to='documents/sketch_ref')),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model')),
            ],
            options={
                'db_table': 'la_ls_land_unit',
                'managed': True,
            },
        ),
    ]
