# Generated by Django 5.1 on 2024-11-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_la_ls_utinet_lu_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_LS_Build_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('postal_ad_build', models.CharField(max_length=255, null=True)),
                ('house_hold_no', models.CharField(max_length=25, null=True)),
                ('ext_builduse_type', models.CharField(max_length=100, null=True)),
                ('ext_builduse_sub_type', models.CharField(max_length=100, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roof_type', models.CharField(max_length=20, null=True)),
                ('wall_type', models.CharField(max_length=20, null=True)),
                ('file_path', models.FileField(null=True, upload_to='documents/sketch_ref')),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model')),
            ],
            options={
                'db_table': 'la_ls_build_unit',
                'managed': True,
            },
        ),
    ]
