# Generated by Django 5.1 on 2024-11-16 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0079_remove_la_admin_source_model_su_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_admin_source_model',
            name='ba_unit_id',
            field=models.ForeignKey(db_column='ba_unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model'),
        ),
    ]
