# Generated by Django 5.1 on 2024-11-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0081_alter_la_admin_source_model_ba_unit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_LS_Utinet_AU_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water', models.CharField(max_length=15, null=True)),
                ('water_drink', models.CharField(max_length=15, null=True)),
                ('elec', models.CharField(max_length=15, null=True)),
                ('tele', models.CharField(max_length=15, null=True)),
                ('internet', models.CharField(max_length=15, null=True)),
                ('sani_sewer', models.CharField(max_length=50, null=True)),
                ('garbage_dispose', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model')),
            ],
            options={
                'db_table': 'la_ls_utinet_au',
                'managed': True,
            },
        ),
    ]
