# Generated by Django 5.1 on 2024-11-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0082_la_ls_utinet_au_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_LS_Ols_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('postal_ad_ols', models.CharField(max_length=255, null=True)),
                ('ols_main_type', models.CharField(max_length=100, null=True)),
                ('ext_olsuse_type', models.CharField(max_length=100, null=True)),
                ('ext_olsuse_sub_type', models.CharField(max_length=100, null=True)),
                ('ols_x_type', models.CharField(max_length=100, null=True)),
                ('ols_build_type', models.CharField(max_length=100, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model')),
            ],
            options={
                'db_table': 'la_ls_ols_unit',
                'managed': True,
            },
        ),
    ]
