# Generated by Django 5.1 on 2024-11-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0087_remove_la_ls_apt_unit_model_file_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spatial_Unit_Sketch_Ref_Model',
        ),
    ]
