# Generated by Django 5.1 on 2024-11-16 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0088_delete_spatial_unit_sketch_ref_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_Spatial_Unit_Sketch_Ref_Model',
            fields=[
                ('sketch_ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('sketch_ref_type', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('approval_status', models.BooleanField(default=True)),
                ('avl_status', models.BooleanField(default=True)),
                ('file_path', models.FileField(null=True, upload_to='documents/sketch_ref')),
                ('status', models.BooleanField(default=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('doc_owner', models.ForeignKey(db_column='doc_owner', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model')),
            ],
            options={
                'db_table': 'la_spatial_unit_sketch_ref',
                'managed': True,
            },
        ),
    ]
