# Generated by Django 5.1 on 2024-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0089_la_spatial_unit_sketch_ref_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_model',
            name='sl_group_party_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
