# Generated by Django 5.1 on 2024-11-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0090_party_model_sl_group_party_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SL_Organization_Model',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255, null=True)),
                ('permit_start_date', models.DateTimeField(null=True)),
                ('permit_end_date', models.DateTimeField(null=True)),
                ('org_parent_type', models.CharField(max_length=100, null=True)),
                ('org_group_type', models.CharField(max_length=100, null=True)),
                ('dimension_2d_3d', models.CharField(default='2D', max_length=50)),
                ('org_level', models.IntegerField(default='0')),
                ('org_overview', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('party_id', models.OneToOneField(db_column='party_id', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
            ],
            options={
                'db_table': 'sl_organization',
                'managed': True,
            },
        ),
    ]
