# Generated by Django 5.1 on 2024-11-17 11:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0092_sl_org_area_parent_bndry_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SL_Org_Area_Child_Bndry_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('username', models.CharField(max_length=255)),
                ('layer_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('dimension_2d_3d', models.CharField(default='2D', max_length=50)),
                ('reference_coordinate', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('parent_id', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_org_area_parent_bndry_model')),
            ],
            options={
                'db_table': 'sl_org_area_child_bndry',
                'managed': True,
            },
        ),
    ]
