# Generated by Django 5.1 on 2024-11-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0093_sl_org_area_child_bndry_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sl_org_area_parent_bndry_model',
            name='org_id',
        ),
        migrations.DeleteModel(
            name='SL_Org_Area_Child_Bndry_Model',
        ),
        migrations.DeleteModel(
            name='SL_Org_Area_Parent_Bndry_Model',
        ),
    ]
