# Generated by Django 5.1 on 2024-11-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0096_sl_org_area_child_bndry_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organization',
            new_name='org_name',
        ),
    ]
