# Generated by Django 5.1 on 2024-11-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0098_alter_user_address_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org_name',
        ),
        migrations.AddField(
            model_name='user',
            name='org_id',
            field=models.IntegerField(default='2'),
        ),
    ]
