# Generated by Django 5.1 on 2024-11-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0099_remove_user_org_name_user_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='org_id',
            field=models.IntegerField(),
        ),
    ]
