# Generated by Django 5.1 on 2024-11-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0100_alter_user_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sl_organization_model',
            name='org_name',
        ),
    ]
