# Generated by Django 5.1 on 2024-11-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0101_remove_sl_organization_model_org_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey_rep_history_model',
            table='survey_rep_func_history',
        ),
    ]
