# Generated by Django 5.1 on 2024-11-19 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0102_alter_survey_rep_history_model_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sl_ba_unit_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
    ]
