# Generated by Django 5.1 on 2024-11-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0103_alter_sl_ba_unit_model_su_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_spatial_unit_model',
            name='su_id',
            field=models.IntegerField(unique=True),
        ),
    ]
