# Generated by Django 5.1 on 2024-11-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0108_alter_la_spatial_unit_model_su_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_spatial_unit_model',
            name='ladm_value',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
