# Generated by Django 5.1 on 2024-11-20 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0109_alter_la_spatial_unit_model_ladm_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_ls_apt_unit_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.AlterField(
            model_name='la_ls_build_unit_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.AlterField(
            model_name='la_ls_ils_unit_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.AlterField(
            model_name='la_ls_land_unit_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.AlterField(
            model_name='la_ls_ols_unit_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.AlterField(
            model_name='la_ls_utinet_au_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.AlterField(
            model_name='la_ls_utinet_bu_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.AlterField(
            model_name='la_ls_utinet_ils_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.AlterField(
            model_name='la_ls_utinet_lu_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.AlterField(
            model_name='la_ls_utinet_ols_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.AlterField(
            model_name='la_spatial_unit_sketch_ref_model',
            name='su_id',
            field=models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
    ]
