# Generated by Django 5.1 on 2024-11-20 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0110_alter_la_ls_apt_unit_model_su_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_list_model',
            name='party_id',
            field=models.ForeignKey(db_column='my_party_id', default='1', on_delete=django.db.models.deletion.CASCADE, to='user.party_model'),
        ),
    ]
