# Generated by Django 5.1 on 2024-11-20 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0111_test_list_model_party_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_permission_model',
            name='permission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.permission_list_model'),
        ),
        migrations.AlterField(
            model_name='role_permission_model',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_roles_model'),
        ),
        migrations.AlterField(
            model_name='test_list_model',
            name='party_id',
            field=models.ForeignKey(db_column='my_party_id', on_delete=django.db.models.deletion.CASCADE, to='user.party_model'),
        ),
    ]
