# Generated by Django 5.1 on 2024-11-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0113_alter_role_permission_model_permission_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_SL_BAUnitType_10_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_baunittype_10',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Education_Level_3_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_education_level_3',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_GenderType_8_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_gendertype_8',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_HealthStatus_5_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_health_status_5',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_MarriedStatus_6_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_married_status_6',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Party_Type_1_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_party_type_1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_PartyRoleType_2_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_partyroletype_2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Race_4_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_race_4',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Religions_7_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_religions_7',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_RightType_9_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_righttype_9',
                'managed': True,
            },
        ),
    ]
