# Generated by Django 5.1 on 2024-11-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0114_lst_sl_baunittype_10_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_SL_AdministrativeStatausType_15_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_administrativestataustype_15',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_AdminRestrictionType_11_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_adminrestrictiontype_11',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_AnnotationType_12_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_annotationtype_12',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_Sl_MortgageType_13_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_mortgagetype_13',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_RightShareType_14_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_rightsharetype_14',
                'managed': True,
            },
        ),
    ]
