# Generated by Django 5.1 on 2024-11-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0115_lst_sl_administrativestataustype_15_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_LA_BAUnitType_18_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_la_baunittype_18',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_AdministrativeSourceType_16_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_administrativesourcetype_16',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_ResponsibilityType_17_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_responsibilitytype_17',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_LevelContentType_19_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_levelcontenttype_19',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_RegesterType_20_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_regestertype_20',
                'managed': True,
            },
        ),
    ]
