# Generated by Django 5.1 on 2024-11-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0116_lst_la_baunittype_18_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_SU_SL_Roof_Type_24_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_roof_type_24',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Sanitation_23_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_sanitation_23',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_StructureType_21_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_structuretype_21',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Wall_Type_25_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_wall_type_25',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Water_22_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_water_22',
                'managed': True,
            },
        ),
    ]
