# Generated by Django 5.1 on 2024-11-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0117_lst_su_sl_roof_type_24_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_SR_SL_SpatialSourceTypes_27_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sr_sl_spatialsourcetypes_27',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Floor_Type_26_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_floor_type_26',
                'managed': True,
            },
        ),
    ]
