# Generated by Django 5.1 on 2024-11-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0118_lst_sr_sl_spatialsourcetypes_27_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_EC_ExtLandUseSubType_29_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extlandusesubtype_29',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtLandUseType_28_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extlandusetype_28',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtOuterLegalSpaceUseType_30_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extouterlegalspaceusetype_30',
                'managed': True,
            },
        ),
    ]
