# Generated by Django 5.1 on 2024-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0119_lst_ec_extlandusesubtype_29_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_EC_ExtBuildUseSubType_33_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extbuildusesubtype_33',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtBuildUseType_32_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extbuildusetype_32',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtDivisionType_34_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extdivisiontype_34',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtFeatureMainType_35_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extfeaturemaintype_35',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtFeatureMainType_36_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extfeatureytype_36',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtFeatureMainType_37_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extfeaturebuildtype_37',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtOuterLegalSpaceUseSubType_31_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extouterlegalspaceusesubtype_31',
                'managed': True,
            },
        ),
    ]
