# Generated by Django 5.1 on 2024-11-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0121_delete_lst_ec_extbuildusesubtype_33_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_EC_ExtBuildUseSubType_33_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extbuildusesubtype_33',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtBuildUseType_32_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extbuildusetype_32',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtDivisionType_34_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extdivisiontype_34',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtFeatureMainType_35_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extfeaturemaintype_35',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtFeatureMainType_36_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extfeatureytype_36',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtFeatureMainType_37_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extfeaturebuildtype_37',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtLandUseSubType_29_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extlandusesubtype_29',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtLandUseType_28_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extlandusetype_28',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtOuterLegalSpaceUseSubType_31_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extouterlegalspaceusesubtype_31',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_EC_ExtOuterLegalSpaceUseType_30_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_ec_extouterlegalspaceusetype_30',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_LA_BAUnitType_18_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_la_baunittype_18',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_AdministrativeSourceType_16_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_administrativesourcetype_16',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_AdministrativeStatausType_15_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_administrativestataustype_15',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_AdminRestrictionType_11_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_adminrestrictiontype_11',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_AnnotationType_12_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_annotationtype_12',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_BAUnitType_10_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_baunittype_10',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Education_Level_3_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_education_level_3',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_GenderType_8_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_gendertype_8',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_HealthStatus_5_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_health_status_5',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_MarriedStatus_6_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_married_status_6',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_Sl_MortgageType_13_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_mortgagetype_13',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Party_Type_1_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_party_type_1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_PartyRoleType_2_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_partyroletype_2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Race_4_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_race_4',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_Religions_7_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_religions_7',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_ResponsibilityType_17_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_responsibilitytype_17',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_RightShareType_14_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_rightsharetype_14',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SL_RightType_9_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_righttype_9',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SR_SL_SpatialSourceTypes_27_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sr_sl_spatialsourcetypes_27',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Floor_Type_26_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_floor_type_26',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_LevelContentType_19_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_levelcontenttype_19',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_RegesterType_20_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_regestertype_20',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Roof_Type_24_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_roof_type_24',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Sanitation_23_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_sanitation_23',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_StructureType_21_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_structuretype_21',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Wall_Type_25_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_wall_type_25',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_SU_SL_Water_22_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_su_sl_water_22',
                'managed': True,
            },
        ),
    ]
