# Generated by Django 5.1 on 2024-11-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0122_lst_ec_extbuildusesubtype_33_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lst_sl_party_type_1_model',
            name='code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
