# Generated by Django 5.1 on 2024-11-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0123_lst_sl_party_type_1_model_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lst_SL_Party_Type_1_Model',
        ),
    ]
