# Generated by Django 5.1 on 2024-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0124_delete_lst_sl_party_type_1_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_SL_Party_Type_1_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lst_sl_party_type_1',
                'managed': True,
            },
        ),
    ]
