# Generated by Django 5.1 on 2024-11-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0125_lst_sl_party_type_1_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Spartialunit_Attrib_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('su_id', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'history_spatialunit_attrib',
                'managed': True,
            },
        ),
    ]
