# Generated by Django 5.1 on 2024-11-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0126_history_spartialunit_attrib_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_spartialunit_attrib_model',
            name='category',
        ),
        migrations.RemoveField(
            model_name='history_spartialunit_attrib_model',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='history_spartialunit_attrib_model',
            name='field_value',
        ),
        migrations.RemoveField(
            model_name='history_spartialunit_attrib_model',
            name='su_id',
        ),
        migrations.RemoveField(
            model_name='history_spartialunit_attrib_model',
            name='username',
        ),
        migrations.AlterField(
            model_name='history_spartialunit_attrib_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
