# Generated by Django 5.1 on 2024-11-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0127_remove_history_spartialunit_attrib_model_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History_Spartialunit_Attrib_Model',
        ),
    ]
