# Generated by Django 5.1 on 2024-11-28 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0129_history_spartialunit_attrib_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_Spatial_Source_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spatial_source_type', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('approval_status', models.BooleanField(default=True)),
                ('date_accept', models.DateTimeField(null=True)),
                ('date_expire', models.DateTimeField(null=True)),
                ('file_path', models.FileField(upload_to='documents/spatial_source')),
                ('surveyor_name', models.CharField(max_length=255, null=True)),
                ('surveyor_tp', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_spatial_source',
                'managed': True,
            },
        ),
    ]
