# Generated by Django 5.1 on 2024-11-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0130_la_spatial_source_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LA_Spatial_Source_Model',
        ),
    ]
