# Generated by Django 5.1 on 2024-11-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0131_delete_la_spatial_source_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_ass_id', models.CharField(max_length=255, null=True)),
                ('ass_no', models.CharField(max_length=10, null=True)),
                ('ass_road', models.CharField(max_length=255, null=True)),
                ('ass_div', models.CharField(max_length=30, null=True)),
                ('ann_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_valuation', models.DateTimeField(null=True)),
                ('year_asses', models.DateTimeField(null=True)),
                ('property_type', models.CharField(max_length=255, null=True)),
                ('ass_name', models.CharField(max_length=255)),
                ('out_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
        ),
        migrations.CreateModel(
            name='LA_Spatial_Source_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spatial_source_type', models.CharField(max_length=255, null=True)),
                ('source_id', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('approval_status', models.BooleanField(default=True)),
                ('date_accept', models.DateTimeField(null=True)),
                ('date_expire', models.DateTimeField(null=True)),
                ('file_path', models.FileField(upload_to='documents/spatial_source')),
                ('surveyor_name', models.CharField(max_length=255, null=True)),
                ('surveyor_tp', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_spatial_source',
                'managed': True,
            },
        ),
    ]
