# Generated by Django 5.1 on 2024-11-28 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0132_assessment_model_la_spatial_source_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_Info_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_tax_id', models.CharField(max_length=255, null=True)),
                ('tax_no', models.CharField(max_length=50, null=True)),
                ('ann_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_valuation', models.DateTimeField(null=True)),
                ('tax_date', models.DateTimeField(null=True)),
                ('tax_type', models.CharField(max_length=255, null=True)),
                ('tax_name', models.CharField(max_length=255)),
                ('out_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
        ),
    ]
