# Generated by Django 5.1 on 2024-11-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0133_tax_info_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_SP_Fire_Rescue_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('officer', models.CharField(max_length=255, null=True)),
                ('issued_date', models.DateTimeField(null=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
        ),
    ]
