# Generated by Django 5.1 on 2024-12-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0134_la_sp_fire_rescue_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax_info_model',
            name='su_id',
        ),
        migrations.DeleteModel(
            name='Assessment_Model',
        ),
        migrations.DeleteModel(
            name='Tax_Info_Model',
        ),
    ]
