# Generated by Django 5.1 on 2024-12-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0136_assessment_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment_Model',
        ),
    ]
