# Generated by Django 5.1 on 2024-12-05 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0137_delete_assessment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_ass_id', models.CharField(max_length=255, null=True)),
                ('ass_no', models.CharField(max_length=10, null=True)),
                ('ass_road', models.CharField(max_length=255, null=True)),
                ('ass_div', models.CharField(max_length=30, null=True)),
                ('ann_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_valuation', models.DateTimeField(null=True)),
                ('year_asses', models.DateTimeField(null=True)),
                ('property_type', models.CharField(max_length=255, null=True)),
                ('ass_name', models.CharField(max_length=255)),
                ('out_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'assessment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tax_Info_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_tax_id', models.CharField(max_length=255, null=True)),
                ('tax_no', models.CharField(max_length=50, null=True)),
                ('ann_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_valuation', models.DateTimeField(null=True)),
                ('tax_date', models.DateTimeField(null=True)),
                ('tax_type', models.CharField(max_length=255, null=True)),
                ('tax_name', models.CharField(max_length=255)),
                ('out_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'tax_info',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='LA_SP_Fire_Rescue_Model',
        ),
    ]
