# Generated by Django 5.1 on 2024-12-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0139_la_sp_fire_rescue_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_model',
            name='year_asses',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
