# Generated by Django 5.1 on 2024-12-24 11:53

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0140_alter_assessment_model_year_asses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Rep_Geom_History_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('su_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('layer_id', models.IntegerField()),
                ('geom_type', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('dimension_2d_3d', models.CharField(default='2D', max_length=50)),
                ('reference_coordinate', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('status', models.BooleanField(default=True)),
                ('parent_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'survey_rep_geom_history',
                'managed': True,
            },
        ),
    ]
