# Generated by Django 5.1 on 2024-12-25 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0141_survey_rep_geom_history_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='rrr_id',
        ),
        migrations.AddField(
            model_name='admin_annotation_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
        migrations.AddField(
            model_name='la_mortgage_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
        migrations.AddField(
            model_name='la_responsibility_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
        migrations.AddField(
            model_name='sl_admin_restrict_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
        migrations.AddField(
            model_name='sl_rights_liabilities_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
        migrations.AddField(
            model_name='sl_rights_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
        migrations.AlterField(
            model_name='sl_rights_model',
            name='right_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
