# Generated by Django 5.1 on 2024-12-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0142_remove_la_rrr_model_rrr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_annotation_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
        migrations.AlterField(
            model_name='la_mortgage_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
        migrations.AlterField(
            model_name='la_responsibility_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
        migrations.AlterField(
            model_name='sl_admin_restrict_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
        migrations.AlterField(
            model_name='sl_rights_liabilities_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
        migrations.AlterField(
            model_name='sl_rights_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
    ]
