# Generated by Django 5.1 on 2024-12-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0143_alter_admin_annotation_model_rrr_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sl_rights_model',
            name='right_party',
        ),
        migrations.RemoveField(
            model_name='sl_rights_model',
            name='right_type',
        ),
        migrations.RemoveField(
            model_name='sl_rights_model',
            name='share',
        ),
    ]
