# Generated by Django 5.1 on 2024-12-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0144_remove_sl_rights_model_right_party_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_annotation_model',
            name='admin_anno_type',
        ),
        migrations.RemoveField(
            model_name='admin_annotation_model',
            name='claiment_pid',
        ),
        migrations.RemoveField(
            model_name='admin_annotation_model',
            name='share',
        ),
        migrations.RemoveField(
            model_name='la_mortgage_model',
            name='mortgagor',
        ),
        migrations.RemoveField(
            model_name='la_mortgage_model',
            name='share',
        ),
        migrations.RemoveField(
            model_name='la_mortgage_model',
            name='sl_mortgage_type',
        ),
        migrations.RemoveField(
            model_name='la_responsibility_model',
            name='responsibility_party',
        ),
        migrations.RemoveField(
            model_name='la_responsibility_model',
            name='responsibility_type',
        ),
        migrations.RemoveField(
            model_name='la_responsibility_model',
            name='share',
        ),
        migrations.RemoveField(
            model_name='sl_admin_restrict_model',
            name='gov_party',
        ),
        migrations.RemoveField(
            model_name='sl_admin_restrict_model',
            name='share',
        ),
        migrations.RemoveField(
            model_name='sl_admin_restrict_model',
            name='sl_adm_res_type',
        ),
        migrations.RemoveField(
            model_name='sl_rights_liabilities_model',
            name='owner_pid',
        ),
        migrations.RemoveField(
            model_name='sl_rights_liabilities_model',
            name='share',
        ),
        migrations.RemoveField(
            model_name='sl_rights_liabilities_model',
            name='sl_right_type',
        ),
    ]
