# Generated by Django 5.1 on 2024-12-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0145_remove_admin_annotation_model_admin_anno_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='la_mortgage_model',
            name='ba_unit_id',
        ),
        migrations.RemoveField(
            model_name='la_mortgage_model',
            name='rrr_id',
        ),
        migrations.RemoveField(
            model_name='la_responsibility_model',
            name='ba_unit_id',
        ),
        migrations.RemoveField(
            model_name='la_responsibility_model',
            name='rrr_id',
        ),
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='admin_source_id',
        ),
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='ba_unit_id',
        ),
        migrations.RemoveField(
            model_name='sl_admin_restrict_model',
            name='rrr_id',
        ),
        migrations.RemoveField(
            model_name='sl_rights_model',
            name='rrr_id',
        ),
        migrations.RemoveField(
            model_name='sl_rights_liabilities_model',
            name='rrr_id',
        ),
        migrations.RemoveField(
            model_name='sl_admin_restrict_model',
            name='ba_unit_id',
        ),
        migrations.RemoveField(
            model_name='sl_rights_liabilities_model',
            name='ba_unit_id',
        ),
        migrations.RemoveField(
            model_name='sl_rights_model',
            name='ba_unit_id',
        ),
        migrations.DeleteModel(
            name='Admin_Annotation_Model',
        ),
        migrations.DeleteModel(
            name='LA_Mortgage_Model',
        ),
        migrations.DeleteModel(
            name='LA_Responsibility_Model',
        ),
        migrations.DeleteModel(
            name='LA_RRR_Model',
        ),
        migrations.DeleteModel(
            name='SL_Admin_Restrict_Model',
        ),
        migrations.DeleteModel(
            name='SL_Rights_Liabilities_Model',
        ),
        migrations.DeleteModel(
            name='SL_Rights_Model',
        ),
    ]
