# Generated by Django 5.1 on 2024-12-26 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0146_remove_la_mortgage_model_ba_unit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_RRR_Model',
            fields=[
                ('rrr_id', models.AutoField(primary_key=True, serialize=False)),
                ('su_id', models.IntegerField()),
                ('ba_unit_type', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('admin_source_id', models.ForeignKey(db_column='admin_source_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.la_admin_source_model')),
                ('ba_unit_id', models.ForeignKey(db_column='ba_unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model')),
            ],
            options={
                'db_table': 'la_rrr',
                'managed': True,
            },
        ),
    ]
