# Generated by Django 5.1 on 2024-12-26 07:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0147_la_rrr_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Annotation_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_anno_type', models.CharField(max_length=50, null=True)),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('a_a_parties', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('description', models.TextField(null=True)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('claiment_pid', models.ForeignKey(db_column='claiment_pid', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
                ('rrr_id', models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model')),
            ],
            options={
                'db_table': 'la_rrr_admin_annotation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_Mortgage_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('int_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('sl_mortgage_type', models.CharField(max_length=50, null=True)),
                ('mort_id', models.IntegerField(null=True)),
                ('mortgagee', models.IntegerField(null=True)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('mortgagor', models.ForeignKey(db_column='mortgagor', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
                ('rrr_id', models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model')),
            ],
            options={
                'db_table': 'la_rrr_la_Mortgage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_Responsibility_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('responsibility_type', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('party', models.ForeignKey(db_column='party', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
                ('rrr_id', models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model')),
            ],
            options={
                'db_table': 'la_rrr_la_responsibility',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SL_Admin_Restrict_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sl_adm_res_type', models.CharField(max_length=50, null=True)),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('adm_res_legal_space', models.CharField(max_length=50, null=True)),
                ('adm_res_legal_prov', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('gov_party', models.ForeignKey(db_column='gov_party', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
                ('rrr_id', models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model')),
            ],
            options={
                'db_table': 'la_rrr_sl_admin_restrict',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SL_Rights_Liabilities_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sl_right_type', models.CharField(max_length=50, null=True)),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sl_rl_parties', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('description', models.TextField(null=True)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('party', models.ForeignKey(db_column='party', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
                ('rrr_id', models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model')),
            ],
            options={
                'db_table': 'la_rrr_sl_rights_lib',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SL_Rights_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('right_type', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('time_spec', models.CharField(max_length=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('party', models.ForeignKey(db_column='party', on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
                ('rrr_id', models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model')),
            ],
            options={
                'db_table': 'la_rrr_sl_rights',
                'managed': True,
            },
        ),
    ]
