# Generated by Django 5.1 on 2024-12-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0148_admin_annotation_model_la_mortgage_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='la_rrr_model',
            old_name='ba_unit_type',
            new_name='la_ba_unit_type',
        ),
        migrations.RenameField(
            model_name='sl_ba_unit_model',
            old_name='ba_unit_name',
            new_name='sl_ba_unit_name',
        ),
        migrations.RenameField(
            model_name='sl_ba_unit_model',
            old_name='ba_unit_type',
            new_name='sl_ba_unit_type',
        ),
    ]
