# Generated by Django 5.1 on 2024-12-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0149_rename_ba_unit_type_la_rrr_model_la_ba_unit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_rrr_model',
            name='code',
            field=models.CharField(default='sl_rights', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='la_rrr_model',
            constraint=models.UniqueConstraint(fields=('code', 'ba_unit_id'), name='code_ba_id'),
        ),
    ]
