# Generated by Django 5.1 on 2024-12-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0150_la_rrr_model_code_la_rrr_model_code_ba_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_rrr_model',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
