# Generated by Django 5.1 on 2024-12-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0151_alter_la_rrr_model_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_BA_Unit_Attrib_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('ba_unit_id', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'history_baunit_attrib',
                'managed': True,
            },
        ),
    ]
