# Generated by Django 5.1 on 2024-12-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0152_history_ba_unit_attrib_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='la_rrr_model',
            name='code_ba_id',
        ),
        migrations.AddConstraint(
            model_name='la_rrr_model',
            constraint=models.UniqueConstraint(fields=('code', 'ba_unit_id', 'admin_source_id'), name='code_ba_id'),
        ),
    ]
