# Generated by Django 5.1 on 2024-12-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0153_remove_la_rrr_model_code_ba_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History_BA_Unit_Attrib_Model',
        ),
    ]
