# Generated by Django 5.1 on 2024-12-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0154_delete_history_ba_unit_attrib_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_admin_source_model',
            name='username',
            field=models.CharField(default='user@email.com', max_length=255),
        ),
    ]
