# Generated by Django 5.1 on 2024-12-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0155_la_admin_source_model_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_admin_source_model',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
