# Generated by Django 5.1 on 2024-12-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0156_alter_la_admin_source_model_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_model',
            name='username',
            field=models.CharField(default='admin@email.com', max_length=255),
        ),
    ]
