# Generated by Django 5.1 on 2024-12-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0157_party_model_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_model',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
