# Generated by Django 5.1 on 2024-12-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0158_alter_party_model_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_rrr_model',
            name='username',
            field=models.CharField(default='user@email.com', max_length=255),
        ),
    ]
