# Generated by Django 5.1 on 2024-12-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0160_alter_la_rrr_model_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_rrr_model',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
