# Generated by Django 5.1 on 2024-12-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0161_alter_la_rrr_model_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_mortgage_model',
            name='mort_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='la_mortgage_model',
            name='mortgagee',
            field=models.CharField(max_length=50),
        ),
    ]
