# Generated by Django 5.1 on 2024-12-28 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0162_alter_la_mortgage_model_mort_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sl_rights_model',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
