# Generated by Django 5.1 on 2024-12-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0163_sl_rights_model_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sl_rights_model',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
