# Generated by Django 5.1 on 2024-12-28 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0164_alter_sl_rights_model_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_annotation_model',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='la_mortgage_model',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='la_responsibility_model',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sl_admin_restrict_model',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sl_rights_liabilities_model',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
