# Generated by Django 5.1 on 2024-12-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0165_admin_annotation_model_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_annotation_model',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='la_mortgage_model',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='la_responsibility_model',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sl_admin_restrict_model',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sl_rights_liabilities_model',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
