# Generated by Django 5.1 on 2024-12-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0166_alter_admin_annotation_model_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey_rep_geom_history_model',
            name='dimension_2d_3d',
        ),
        migrations.RemoveField(
            model_name='survey_rep_geom_history_model',
            name='geom_type',
        ),
        migrations.RemoveField(
            model_name='survey_rep_geom_history_model',
            name='parent_id',
        ),
    ]
