# Generated by Django 5.1 on 2025-01-05 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0167_remove_survey_rep_geom_history_model_dimension_2d_3d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_admin_source_model',
            name='acceptance_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='la_admin_source_model',
            name='admin_source_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='la_admin_source_model',
            name='doc_owner',
            field=models.ForeignKey(db_column='doc_owner', on_delete=django.db.models.deletion.CASCADE, to='user.party_model'),
        ),
    ]
