# Generated by Django 5.1 on 2025-01-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0168_alter_la_admin_source_model_acceptance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_ls_utinet_lu_model',
            name='drainage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='la_ls_utinet_lu_model',
            name='elec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='la_ls_utinet_lu_model',
            name='garbage_dispose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='la_ls_utinet_lu_model',
            name='sani_gully',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='la_ls_utinet_lu_model',
            name='water',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
