# Generated by Django 5.1 on 2025-01-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0169_alter_la_ls_utinet_lu_model_drainage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_model',
            name='date_valuation',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='la_sp_fire_rescue_model',
            name='issued_date',
            field=models.DateField(null=True),
        ),
    ]
