# Generated by Django 5.1 on 2025-01-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0170_alter_assessment_model_date_valuation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax_info_model',
            name='tax_date',
            field=models.DateField(null=True),
        ),
    ]
