# Generated by Django 5.1 on 2025-01-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0171_alter_tax_info_model_tax_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_spatial_unit_sketch_ref_model',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='la_spatial_unit_sketch_ref_model',
            name='avl_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='la_spatial_unit_sketch_ref_model',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
