# Generated by Django 5.1 on 2025-01-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0172_alter_la_spatial_unit_sketch_ref_model_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_spatial_unit_sketch_ref_model',
            name='approval_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='la_spatial_unit_sketch_ref_model',
            name='avl_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='la_spatial_unit_sketch_ref_model',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
