# Generated by Django 5.1 on 2025-01-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0173_alter_la_spatial_unit_sketch_ref_model_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_admin_source_model',
            name='acceptance_date',
            field=models.DateField(null=True),
        ),
    ]
