# Generated by Django 5.1 on 2025-01-08 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0174_alter_la_admin_source_model_acceptance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attrib_Image_Upload_Model',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('file_path', models.FileField(null=True, upload_to='documents/images')),
                ('status', models.BooleanField(default=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'attrib_panel_images',
                'managed': True,
            },
        ),
    ]
