# Generated by Django 5.1 on 2025-01-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0175_attrib_image_upload_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attrib_image_upload_model',
            name='description',
        ),
    ]
