# Generated by Django 5.1 on 2025-01-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0176_remove_attrib_image_upload_model_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_spatial_source_model',
            name='date_accept',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='la_spatial_source_model',
            name='date_expire',
            field=models.DateField(null=True),
        ),
    ]
