# Generated by Django 5.1 on 2025-01-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0177_alter_la_spatial_source_model_date_accept_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attrib_Image_Upload_Model',
            new_name='Attrib_Image_Model',
        ),
    ]
