# Generated by Django 5.1 on 2025-01-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0178_rename_attrib_image_upload_model_attrib_image_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages_Model',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('username_sender', models.CharField(max_length=255)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('username_receiver', models.CharField(max_length=255)),
                ('view_status', models.BooleanField(default=False)),
                ('date_viewed', models.DateTimeField(null=True)),
                ('done_status', models.BooleanField(default=False)),
                ('hide_status', models.BooleanField(default=False)),
                ('file_path', models.FileField(null=True, upload_to='documents/message_attachements')),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inquiry_Model',
            fields=[
                ('inq_id', models.AutoField(primary_key=True, serialize=False)),
                ('username_creator', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('inquiry_type', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('username_assigned', models.CharField(max_length=255)),
                ('view_status', models.BooleanField(default=False)),
                ('date_viewed', models.DateTimeField(null=True)),
                ('done_status', models.BooleanField(default=False)),
                ('hide_status', models.BooleanField(default=False)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'Inquiries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reminders_Model',
            fields=[
                ('rmd_id', models.AutoField(primary_key=True, serialize=False)),
                ('username_creator', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reminder_type', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('done_status', models.BooleanField(default=False)),
                ('hide_status', models.BooleanField(default=False)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'reminders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tags_Model',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('username_creator', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tag_type', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('deleted_user', models.CharField(max_length=255, null=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'tags',
                'managed': True,
            },
        ),
    ]
