# Generated by Django 5.1 on 2025-01-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0179_messages_model_inquiry_model_reminders_model_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inquiry_Model',
            new_name='Inquiries_Model',
        ),
    ]
