# Generated by Django 5.1 on 2025-01-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0180_rename_inquiry_model_inquiries_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminders_Model',
        ),
    ]
