# Generated by Django 5.1 on 2025-01-10 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0181_delete_reminders_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders_Model',
            fields=[
                ('rmd_id', models.AutoField(primary_key=True, serialize=False)),
                ('username_creator', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reminder_type', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('date_remind', models.DateTimeField()),
                ('done_status', models.BooleanField(default=False)),
                ('hide_status', models.BooleanField(default=False)),
                ('su_id', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'reminders',
                'managed': True,
            },
        ),
    ]
