# Generated by Django 5.1 on 2025-01-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0185_alter_survey_rep_data_model_su_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='su_id',
            field=models.IntegerField(),
        ),
    ]
