# Generated by Django 5.1 on 2025-01-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0187_alter_survey_rep_data_model_su_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layersmodel',
            old_name='username',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='layersmodel',
            unique_together={('user_id', 'layer_name')},
        ),
    ]
