# Generated by Django 5.1 on 2025-01-21 03:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0188_rename_username_layersmodel_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layersmodel',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='layersmodel',
            name='group_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='layersmodel',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
