# Generated by Django 5.1 on 2025-01-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0189_alter_layersmodel_date_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey_rep_data_model',
            old_name='username',
            new_name='user_id',
        ),
    ]
