# Generated by Django 5.1 on 2025-01-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0191_alter_survey_rep_data_model_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey_rep_geom_history_model',
            old_name='username',
            new_name='user_id',
        ),
    ]
