# Generated by Django 5.1 on 2025-01-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0192_rename_username_survey_rep_geom_history_model_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_geom_history_model',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
