# Generated by Django 5.1 on 2025-01-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0193_alter_survey_rep_geom_history_model_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='import_vectordata_model',
            old_name='username',
            new_name='user_id',
        ),
    ]
