# Generated by Django 5.1 on 2025-01-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0194_rename_username_import_vectordata_model_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_vectordata_model',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
