# Generated by Django 5.1 on 2025-01-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0195_alter_import_vectordata_model_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey_rep_history_model',
            old_name='username',
            new_name='user_id',
        ),
    ]
