# Generated by Django 5.1 on 2025-01-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0197_alter_survey_rep_history_model_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_roles_model',
            old_name='admin_name',
            new_name='admin_id',
        ),
    ]
