# Generated by Django 5.1 on 2025-01-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0198_rename_admin_name_user_roles_model_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles_model',
            name='admin_id',
            field=models.IntegerField(),
        ),
    ]
