# Generated by Django 5.1 on 2025-01-21 12:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0199_alter_user_roles_model_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles_model',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
