# Generated by Django 5.1 on 2025-01-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0200_alter_user_roles_model_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='la_admin_source_model',
            old_name='username',
            new_name='user_id',
        ),
    ]
