# Generated by Django 5.1 on 2025-01-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0202_alter_la_admin_source_model_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history_spartialunit_attrib_model',
            old_name='username',
            new_name='user_id',
        ),
    ]
