# Generated by Django 5.1 on 2025-01-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0203_rename_username_history_spartialunit_attrib_model_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_spartialunit_attrib_model',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
