# Generated by Django 5.1 on 2025-01-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0204_alter_history_spartialunit_attrib_model_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='la_rrr_model',
            old_name='username',
            new_name='user_id',
        ),
    ]
