# Generated by Django 5.1 on 2025-01-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0205_rename_username_la_rrr_model_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_rrr_model',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
