# Generated by Django 5.1 on 2025-01-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0206_alter_la_rrr_model_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party_model',
            old_name='username',
            new_name='user_id',
        ),
    ]
