# Generated by Django 5.1 on 2025-01-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0209_rename_username_sl_org_area_parent_bndry_model_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sl_org_area_parent_bndry_model',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
