# Generated by Django 5.1 on 2025-01-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0210_alter_sl_org_area_parent_bndry_model_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sl_org_area_child_bndry_model',
            old_name='username',
            new_name='user_id',
        ),
    ]
