# Generated by Django 5.1 on 2025-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0213_rename_username_attrib_image_model_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrib_image_model',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
