# Generated by Django 5.1 on 2025-01-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0214_alter_attrib_image_model_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_User_Attrib_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done_by', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'history_user_attrib',
                'managed': True,
            },
        ),
    ]
