# Generated by Django 5.1 on 2025-01-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0215_history_user_attrib_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party_model',
            old_name='user_id',
            new_name='done_by',
        ),
    ]
