# Generated by Django 5.1 on 2025-01-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0216_rename_user_id_party_model_done_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_model',
            name='party_full_name',
            field=models.CharField(default='Full Name', max_length=255),
        ),
    ]
