# Generated by Django 5.1 on 2025-01-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0217_party_model_party_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_model',
            name='party_full_name',
            field=models.CharField(max_length=255),
        ),
    ]
