# Generated by Django 5.1 on 2025-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0218_alter_party_model_party_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Party_Attrib_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done_by', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'history_party_attrib',
                'managed': True,
            },
        ),
    ]
