# Generated by Django 5.1 on 2025-01-29 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0219_history_party_attrib_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LA_LS_Ols_Unit_Model',
            new_name='LA_LS_MyLayer_Unit_Model',
        ),
        migrations.AlterField(
            model_name='assessment_model',
            name='ann_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessment_model',
            name='ass_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assessment_model',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tax_info_model',
            name='ann_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tax_info_model',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tax_info_model',
            name='tax_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='la_ls_mylayer_unit_model',
            table='la_ls_mylayer_unit',
        ),
        migrations.CreateModel(
            name='LA_LS_MyLayer_PointLine_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('ols_made_type', models.CharField(max_length=100, null=True)),
                ('ols_main_type', models.CharField(max_length=100, null=True)),
                ('ols_x_type', models.CharField(max_length=100, null=True)),
                ('ols_build_type', models.CharField(max_length=100, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_mylayer_pointline_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Ols_PointLine_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('ols_made_type', models.CharField(max_length=100, null=True)),
                ('ols_main_type', models.CharField(max_length=100, null=True)),
                ('ols_x_type', models.CharField(max_length=100, null=True)),
                ('ols_build_type', models.CharField(max_length=100, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_ols_pointline_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Ols_Polygon_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_road', models.CharField(max_length=255, null=True)),
                ('postal_ad_ols', models.CharField(max_length=255, null=True)),
                ('ols_main_type', models.CharField(max_length=100, null=True)),
                ('ext_olsuse_type', models.CharField(max_length=100, null=True)),
                ('ext_olsuse_sub_type', models.CharField(max_length=100, null=True)),
                ('ols_x_type', models.CharField(max_length=100, null=True)),
                ('ols_build_type', models.CharField(max_length=100, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_ols_unit',
                'managed': True,
            },
        ),
    ]
