# Generated by Django 5.1 on 2025-01-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0220_rename_la_ls_ols_unit_model_la_ls_mylayer_unit_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='ref_id',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='survey_rep_geom_history_model',
            name='ref_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
