# Generated by Django 5.1 on 2025-01-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0221_survey_rep_data_model_ref_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='ref_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='survey_rep_geom_history_model',
            name='ref_id',
            field=models.IntegerField(null=True),
        ),
    ]
