# Generated by Django 5.1 on 2025-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0222_alter_survey_rep_data_model_ref_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiries_model',
            name='username_assigned',
        ),
        migrations.RemoveField(
            model_name='inquiries_model',
            name='username_creator',
        ),
        migrations.RemoveField(
            model_name='messages_model',
            name='username_receiver',
        ),
        migrations.RemoveField(
            model_name='messages_model',
            name='username_sender',
        ),
        migrations.RemoveField(
            model_name='reminders_model',
            name='username_creator',
        ),
        migrations.RemoveField(
            model_name='tags_model',
            name='username_creator',
        ),
        migrations.AddField(
            model_name='inquiries_model',
            name='user_id_assigned',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inquiries_model',
            name='user_id_creator',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='messages_model',
            name='user_id_receiver',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='messages_model',
            name='user_id_sender',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reminders_model',
            name='user_id_creator',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tags_model',
            name='user_id_creator',
            field=models.IntegerField(default=1),
        ),
    ]
