# Generated by Django 5.1 on 2025-01-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0223_remove_inquiries_model_username_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiries_model',
            name='user_id_assigned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inquiries_model',
            name='user_id_creator',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='messages_model',
            name='user_id_receiver',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='messages_model',
            name='user_id_sender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reminders_model',
            name='user_id_creator',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tags_model',
            name='user_id_creator',
            field=models.IntegerField(),
        ),
    ]
