# Generated by Django 5.1 on 2025-02-06 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0224_alter_inquiries_model_user_id_assigned_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LA_LS_MyLayer_Unit_Model',
            new_name='LA_LS_MyLayer_Polygon_Unit_Model',
        ),
        migrations.RenameField(
            model_name='assessment_model',
            old_name='out_balance',
            new_name='ass_out_balance',
        ),
        migrations.RenameField(
            model_name='assessment_model',
            old_name='ann_value',
            new_name='assessment_annual_value',
        ),
        migrations.RenameField(
            model_name='assessment_model',
            old_name='ass_name',
            new_name='assessment_name',
        ),
        migrations.RenameField(
            model_name='assessment_model',
            old_name='ass_no',
            new_name='assessment_no',
        ),
        migrations.RenameField(
            model_name='assessment_model',
            old_name='percentage',
            new_name='assessment_percentage',
        ),
        migrations.RenameField(
            model_name='assessment_model',
            old_name='date_valuation',
            new_name='date_of_valuation',
        ),
        migrations.RenameField(
            model_name='assessment_model',
            old_name='year_asses',
            new_name='year_of_assessment',
        ),
        migrations.RenameField(
            model_name='tax_info_model',
            old_name='ann_value',
            new_name='tax_annual_value',
        ),
        migrations.RenameField(
            model_name='tax_info_model',
            old_name='out_balance',
            new_name='tax_out_balance',
        ),
        migrations.RenameField(
            model_name='tax_info_model',
            old_name='percentage',
            new_name='tax_percentage',
        ),
    ]
