# Generated by Django 5.1 on 2025-02-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0225_rename_la_ls_mylayer_unit_model_la_ls_mylayer_polygon_unit_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_ls_utinet_bu_model',
            name='sani_gully',
            field=models.CharField(default='G', max_length=50, null=True),
        ),
    ]
