# Generated by Django 5.1 on 2025-02-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0226_la_ls_utinet_bu_model_sani_gully'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_ls_utinet_bu_model',
            name='sani_gully',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
