# Generated by Django 5.1 on 2025-02-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0227_alter_la_ls_utinet_bu_model_sani_gully'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_sp_fire_rescue_model',
            name='expired_date',
            field=models.DateField(default='2025-01-01', null=True),
        ),
    ]
