# Generated by Django 5.1 on 2025-02-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0228_la_sp_fire_rescue_model_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_sp_fire_rescue_model',
            name='expired_date',
            field=models.DateField(null=True),
        ),
    ]
