# Generated by Django 5.1 on 2025-02-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0229_alter_la_sp_fire_rescue_model_expired_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_Int_providers_39_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_int_providers_39',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lst_Tele_Providers_38_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_telecom_providers_38',
                'managed': True,
            },
        ),
    ]
