# Generated by Django 5.1 on 2025-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0230_lst_int_providers_39_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_mortgage_model',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='la_mortgage_model',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
