# Generated by Django 5.1 on 2025-02-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0231_la_mortgage_model_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sl_rights_model',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sl_rights_model',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
