# Generated by Django 5.1 on 2025-02-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0232_sl_rights_model_date_end_sl_rights_model_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_mortgage_model',
            name='share_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sl_rights_model',
            name='share_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
