# Generated by Django 5.1 on 2025-02-17 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0234_sl_gnd_10m'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sl_gnd_10m',
        ),
    ]
