# Generated by Django 5.1 on 2025-02-17 02:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0235_delete_sl_gnd_10m'),
    ]

    operations = [
        migrations.CreateModel(
            name='sl_gnd_10m',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('gnd', models.CharField(max_length=255)),
                ('dsd', models.CharField(max_length=255)),
                ('dist', models.CharField(max_length=255)),
                ('pd', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'sl_gnd_10m',
                'managed': False,
            },
        ),
    ]
