# Generated by Django 5.1 on 2025-02-17 07:50

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0236_sl_gnd_10m'),
    ]

    operations = [
        migrations.CreateModel(
            name='sl_gnd_10m_Model',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('gnd', models.CharField(max_length=255)),
                ('dsd', models.CharField(max_length=255)),
                ('dist', models.CharField(max_length=255)),
                ('pd', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'sl_gnd_10m',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Org_Area_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org_id', models.IntegerField()),
                ('org_area', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'db_table': 'org_area',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='sl_gnd_10m',
        ),
    ]
