# Generated by Django 5.1 on 2025-02-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0237_sl_gnd_10m_model_org_area_model_delete_sl_gnd_10m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sl_ba_unit_model',
            name='dist',
        ),
        migrations.RemoveField(
            model_name='sl_ba_unit_model',
            name='dsd',
        ),
        migrations.RemoveField(
            model_name='sl_ba_unit_model',
            name='gnd',
        ),
        migrations.RemoveField(
            model_name='sl_ba_unit_model',
            name='pd',
        ),
        migrations.AddField(
            model_name='sl_ba_unit_model',
            name='gnd_id',
            field=models.IntegerField(null=True),
        ),
    ]
