# Generated by Django 5.1 on 2025-02-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0238_remove_sl_ba_unit_model_dist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrib_image_model',
            name='su_id',
            field=models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
    ]
