# Generated by Django 5.1 on 2025-02-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0239_alter_attrib_image_model_su_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_Org_Names_40_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_org_names_40',
                'managed': True,
            },
        ),
    ]
