# Generated by Django 5.1 on 2025-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0240_lst_org_names_40_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_SL_Group_Party_Type_41_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lst_sl_group_party_type_41',
                'managed': True,
            },
        ),
    ]
