# Generated by Django 5.1 on 2025-02-21 06:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0241_lst_sl_group_party_type_41_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_Import_Model',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('layer_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'bwmc_parcels',
                'managed': False,
            },
        ),
    ]
