# Generated by Django 5.1 on 2025-02-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0243_org_location_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Org_Location_Model',
        ),
    ]
