# Generated by Django 5.1 on 2025-02-21 06:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0246_delete_org_location_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_Location_Model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'org_location',
                'managed': True,
            },
        ),
    ]
