# Generated by Django 5.1 on 2025-02-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0247_org_location_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_location_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
