# Generated by Django 5.1 on 2025-02-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0248_alter_org_location_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_location_model',
            name='org_id',
            field=models.IntegerField(default=1),
        ),
    ]
