# Generated by Django 5.1 on 2025-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0249_org_location_model_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_location_model',
            name='org_id',
            field=models.IntegerField(),
        ),
    ]
