# Generated by Django 5.1 on 2025-02-25 05:29

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0250_alter_org_location_model_org_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityJson_DATA_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('layer_id', models.IntegerField()),
                ('dimension_2d_3d', models.CharField(default='2D', max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('status', models.BooleanField(default=True)),
                ('parent_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'city_json',
                'managed': True,
            },
        ),
    ]
