# Generated by Django 5.1 on 2025-02-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0251_cityjson_data_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityJson_DATA_Model',
        ),
    ]
