# Generated by Django 5.1 on 2025-02-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0252_delete_cityjson_data_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('use', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('use', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StoreRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('use', models.CharField(max_length=255)),
            ],
        ),
    ]
