# Generated by Django 5.1 on 2025-02-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0253_building_buildinginstallation_storeroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='BuildingInstallation',
        ),
        migrations.DeleteModel(
            name='StoreRoom',
        ),
    ]
