# Generated by Django 5.1 on 2025-02-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0254_delete_building_delete_buildinginstallation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityJSONModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityjson_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityObject',
            fields=[
                ('city_object_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('parents', models.JSONField(blank=True, null=True)),
                ('children', models.JSONField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
