# Generated by Django 5.1 on 2025-02-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0255_cityjsonmodel_cityobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Object_Model',
            fields=[
                ('city_object_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('parents', models.JSONField(blank=True, null=True)),
                ('children', models.JSONField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city_object',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CityJSON_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityjson_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'city_json_model',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='CityJSONModel',
        ),
        migrations.DeleteModel(
            name='CityObject',
        ),
    ]
