# Generated by Django 5.1 on 2025-02-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0256_city_object_model_cityjson_model_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cityjson_model',
            table='city_json',
        ),
    ]
