# Generated by Django 5.1 on 2025-02-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0257_alter_cityjson_model_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City_Object_Model',
        ),
        migrations.DeleteModel(
            name='CityJSON_Model',
        ),
    ]
