# Generated by Django 5.1 on 2025-02-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0259_city_object_model_cityjson_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City_Object_Model',
        ),
        migrations.DeleteModel(
            name='CityJSON_Model',
        ),
    ]
