# Generated by Django 5.1 on 2025-02-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0263_cityjson_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityJSON_Model',
        ),
    ]
