# Generated by Django 5.1 on 2025-02-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0264_delete_cityjson_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityJSON_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityjson_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'city_json',
                'managed': True,
            },
        ),
    ]
