# Generated by Django 5.1 on 2025-02-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0267_city_object_model_cityjson_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_model',
            name='specific_tp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='party_model',
            constraint=models.UniqueConstraint(fields=('sl_party_type', 'specific_tp'), name='unique_sl_party_type_specific_tp'),
        ),
    ]
