# Generated by Django 5.1 on 2025-02-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0268_alter_party_model_specific_tp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_model',
            name='sl_group_party_type',
            field=models.IntegerField(null=True),
        ),
    ]
