# Generated by Django 5.1 on 2025-02-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0269_alter_party_model_sl_group_party_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_model',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
