# Generated by Django 5.1 on 2025-02-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0270_party_model_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_model',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
