# Generated by Django 5.1 on 2025-03-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0271_alter_party_model_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='ol_uid',
            field=models.IntegerField(null=True),
        ),
    ]
