# Generated by Django 5.1 on 2025-03-02 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0272_survey_rep_data_model_ol_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey_rep_data_model',
            name='ol_uid',
        ),
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
