# Generated by Django 5.1 on 2025-03-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0273_remove_survey_rep_data_model_ol_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='la_admin_source_model',
            old_name='description',
            new_name='source_description',
        ),
    ]
