# Generated by Django 5.1 on 2025-03-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0274_rename_description_la_admin_source_model_source_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sl_rights_model',
            old_name='id',
            new_name='rights_id',
        ),
    ]
