# Generated by Django 5.1 on 2025-03-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0275_rename_id_sl_rights_model_rights_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sl_rights_model',
            old_name='rights_id',
            new_name='id',
        ),
    ]
