# Generated by Django 5.1 on 2025-03-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0276_rename_rights_id_sl_rights_model_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Org_Location_Model',
        ),
    ]
