# Generated by Django 5.1 on 2025-03-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0278_org_location_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_location_model',
            name='org_name',
        ),
        migrations.AlterField(
            model_name='sl_organization_model',
            name='party_id',
            field=models.IntegerField(null=True),
        ),
    ]
