# Generated by Django 5.1 on 2025-03-10 10:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0279_remove_org_location_model_org_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles_model',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
