# Generated by Django 5.1 on 2025-03-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0280_alter_user_roles_model_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_permission_model',
            name='add',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role_permission_model',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role_permission_model',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
