# Generated by Django 5.1 on 2025-03-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0281_alter_role_permission_model_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_permission_model',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='role_permission_model',
            name='date_delete',
        ),
        migrations.RemoveField(
            model_name='role_permission_model',
            name='date_edit',
        ),
        migrations.RemoveField(
            model_name='role_permission_model',
            name='date_view',
        ),
    ]
