# Generated by Django 5.1 on 2025-03-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0282_remove_role_permission_model_date_add_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SL_Department_Model',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=255)),
                ('org_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sl_org_department',
                'managed': True,
            },
        ),
    ]
