# Generated by Django 5.1 on 2025-03-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0283_sl_department_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dep_id',
            field=models.IntegerField(default=1),
        ),
    ]
