# Generated by Django 5.1 on 2025-03-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0284_user_dep_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
