# Generated by Django 5.1 on 2025-03-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0285_remove_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_roles_model',
            name='org_id',
            field=models.IntegerField(default=1),
        ),
    ]
