# Generated by Django 5.1 on 2025-03-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0286_user_roles_model_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles_model',
            name='org_id',
            field=models.IntegerField(),
        ),
    ]
