# Generated by Django 5.1 on 2025-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0289_alter_user_roles_model_admin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles_model',
            name='role_name',
            field=models.CharField(max_length=50),
        ),
    ]
