# Generated by Django 5.1 on 2025-03-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0290_alter_user_roles_model_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_list_model',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
