# Generated by Django 5.1 on 2025-03-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0291_permission_list_model_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layersmodel',
            old_name='order_by',
            new_name='org_id',
        ),
        migrations.RemoveField(
            model_name='layersmodel',
            name='uuid',
        ),
    ]
