# Generated by Django 5.1 on 2025-03-14 14:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0292_rename_order_by_layersmodel_org_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layersmodel',
            name='group_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
