# Generated by Django 5.1 on 2025-03-15 02:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0293_alter_layersmodel_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layersmodel',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='layersmodel',
            name='group_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
    ]
