# Generated by Django 5.1 on 2025-03-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0294_remove_layersmodel_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersmodel',
            name='date_modified',
            field=models.DateTimeField(default='2025-01-01', null=True),
        ),
    ]
