# Generated by Django 5.1 on 2025-03-16 03:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0295_layersmodel_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layersmodel',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user_roles_model',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
