# Generated by Django 5.1 on 2025-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0297_alter_layersmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layersmodel',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
