# Generated by Django 5.1 on 2025-03-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0298_alter_layersmodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='la_ls_ils_unit_model',
            name='su_id',
        ),
        migrations.RemoveField(
            model_name='la_ls_utinet_au_model',
            name='su_id',
        ),
        migrations.RemoveField(
            model_name='la_ls_utinet_ils_model',
            name='su_id',
        ),
        migrations.DeleteModel(
            name='LA_LS_Apt_Unit_Model',
        ),
        migrations.DeleteModel(
            name='LA_LS_Ils_Unit_Model',
        ),
        migrations.DeleteModel(
            name='LA_LS_Utinet_AU_Model',
        ),
        migrations.DeleteModel(
            name='LA_LS_Utinet_Ils_Model',
        ),
    ]
