# Generated by Django 5.1 on 2025-03-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0299_remove_la_ls_ils_unit_model_su_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_LS_Ils_Unit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postal_ad_ils', models.CharField(max_length=255, null=True)),
                ('floor_no', models.IntegerField(null=True)),
                ('house_hold_no', models.CharField(max_length=25, null=True)),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ext_ilsuse_type', models.CharField(max_length=100, null=True)),
                ('ext_ilsuse_sub_type', models.CharField(max_length=100, null=True)),
                ('surface_relation', models.CharField(max_length=20, null=True)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roof_type', models.CharField(max_length=20, null=True)),
                ('wall_type', models.CharField(max_length=20, null=True)),
                ('floor_type', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ref_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_ls_build_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_ils_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_LS_Utinet_Ils_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water', models.CharField(max_length=15, null=True)),
                ('water_drink', models.CharField(max_length=15, null=True)),
                ('elec', models.CharField(max_length=15, null=True)),
                ('tele', models.CharField(max_length=15, null=True)),
                ('internet', models.CharField(max_length=15, null=True)),
                ('sani_sewer', models.CharField(max_length=50, null=True)),
                ('garbage_dispose', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ref_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_ls_build_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_utinet_ils',
                'managed': True,
            },
        ),
    ]
