# Generated by Django 5.1 on 2025-05-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0302_alter_import_vectordata_model_dataset_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_Geotif_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('dataset_name', models.CharField(max_length=255)),
                ('layer_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(null=True, upload_to='documents/geotif')),
            ],
            options={
                'db_table': 'import_geotif',
                'managed': True,
            },
        ),
    ]
