# Generated by Django 5.1 on 2025-05-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0303_import_geotif_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='import_geotif_model',
            constraint=models.UniqueConstraint(fields=('user_id', 'dataset_name'), name='geotif_unique'),
        ),
    ]
