# Generated by Django 5.1 on 2025-05-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0304_import_geotif_model_geotif_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Import_Geotif_Model',
        ),
    ]
