# Generated by Django 5.1 on 2025-05-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0305_delete_import_geotif_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_Geotif_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('datasetName', models.CharField(max_length=255)),
                ('layer_id', models.IntegerField(null=True)),
                ('crs', models.CharField(max_length=255)),
                ('file_path', models.FileField(null=True, upload_to='documents/geotif')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'import_geotif',
                'managed': True,
            },
        ),
    ]
