# Generated by Django 5.1 on 2025-05-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0306_import_geotif_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='import_geotif_model',
            constraint=models.UniqueConstraint(fields=('user_id', 'datasetName'), name='geotif_unique'),
        ),
    ]
