# Generated by Django 5.1 on 2025-05-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0309_import_geotif_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Import_Geotif_Model',
            new_name='Import_RasterData_Model',
        ),
    ]
