# Generated by Django 5.1 on 2025-05-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0310_rename_import_geotif_model_import_rasterdata_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_rasterdata_model',
            name='capture_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='import_rasterdata_model',
            name='file_path',
            field=models.FileField(upload_to='documents/raster_data'),
        ),
    ]
