# Generated by Django 5.1 on 2025-05-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0311_import_rasterdata_model_capture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_rasterdata_model',
            name='capture_date',
            field=models.DateField(),
        ),
    ]
