# Generated by Django 5.1 on 2025-05-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0312_alter_import_rasterdata_model_capture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_rasterdata_model',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
