# Generated by Django 5.1 on 2025-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0313_import_rasterdata_model_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='original_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='original_point_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='original_x_coord',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='original_y_coord',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='original_z_coord',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
