# Generated by Django 5.1 on 2025-06-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0314_survey_rep_data_model_original_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='gnd_id',
            field=models.IntegerField(null=True),
        ),
    ]
