# Generated by Django 5.1 on 2025-06-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0315_survey_rep_data_model_gnd_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sl_ba_unit_model',
            name='eletorate',
        ),
        migrations.RemoveField(
            model_name='sl_ba_unit_model',
            name='gnd_id',
        ),
        migrations.RemoveField(
            model_name='sl_ba_unit_model',
            name='local_auth',
        ),
    ]
