# Generated by Django 5.1 on 2025-06-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0316_remove_sl_ba_unit_model_eletorate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SL_Elect_LocalAuth_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gnd_id', models.IntegerField(null=True)),
                ('eletorate', models.CharField(max_length=50, null=True)),
                ('local_auth', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'sl_elect_local_auth',
                'managed': True,
            },
        ),
    ]
