# Generated by Django 5.1 on 2025-06-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0317_sl_elect_localauth_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_rrr_model',
            name='share',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='la_rrr_model',
            name='share_type',
            field=models.CharField(default='WholeOwnership', max_length=100),
        ),
    ]
