# Generated by Django 5.1 on 2025-06-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0318_la_rrr_model_share_la_rrr_model_share_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_rrr_model',
            name='share',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='la_rrr_model',
            name='share_type',
            field=models.CharField(max_length=100),
        ),
    ]
