# Generated by Django 5.1 on 2025-06-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0319_alter_la_rrr_model_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_ls_apt_unit_model',
            name='apt_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_build_unit_model',
            name='building_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_ils_unit_model',
            name='ils_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='land_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_ols_pointline_unit_model',
            name='ols_point_line_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_ols_polygon_unit_model',
            name='ols_poly_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
