# Generated by Django 5.1 on 2025-06-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0320_la_ls_apt_unit_model_apt_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_Ward_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=100)),
                ('org_id', models.IntegerField()),
            ],
            options={
                'db_table': 'assessment_ward',
                'managed': True,
            },
        ),
    ]
