# Generated by Django 5.1 on 2025-06-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0321_assessment_ward_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_ls_build_unit_model',
            name='bld_property_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
