# Generated by Django 5.1 on 2025-07-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0322_la_ls_build_unit_model_bld_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sl_rights_model',
            name='party',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sl_rights_model',
            name='rrr_id',
            field=models.IntegerField(null=True),
        ),
    ]
