# Generated by Django 5.1 on 2025-07-03 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0323_alter_sl_rights_model_party_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='la_rrr_model',
            name='code_ba_id',
        ),
        migrations.AddField(
            model_name='la_rrr_model',
            name='party',
            field=models.ForeignKey(db_column='party', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.party_model'),
        ),
        migrations.AddField(
            model_name='la_rrr_model',
            name='time_spec',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='la_rrr_model',
            constraint=models.UniqueConstraint(fields=('ba_unit_id', 'admin_source_id'), name='RRR_Unique'),
        ),
    ]
