# Generated by Django 5.1 on 2025-07-03 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0324_remove_la_rrr_model_code_ba_id_la_rrr_model_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_rrr_model',
            name='party',
            field=models.ForeignKey(db_column='party', on_delete=django.db.models.deletion.CASCADE, to='user.party_model'),
        ),
    ]
