# Generated by Django 5.1 on 2025-07-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0325_alter_la_rrr_model_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='doc_owner',
        ),
        migrations.AddField(
            model_name='la_admin_source_model',
            name='party',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='la_admin_source_model',
            name='ba_unit_id',
            field=models.IntegerField(null=True),
        ),
    ]
