# Generated by Django 5.1 on 2025-07-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0326_remove_la_admin_source_model_doc_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sl_ba_unit_model',
            name='su_id',
            field=models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
    ]
