# Generated by Django 5.1 on 2025-07-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0327_alter_sl_ba_unit_model_su_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party_model',
            old_name='sl_group_party_type',
            new_name='sl_group_party_id',
        ),
    ]
