# Generated by Django 5.1 on 2025-07-03 09:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0328_rename_sl_group_party_type_party_model_sl_group_party_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SL_Group_Party_Members_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, null=True)),
                ('sl_group_party_type', models.IntegerField()),
                ('party_members', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.IntegerField()),
            ],
            options={
                'db_table': 'sl_group_party_members',
                'managed': True,
            },
        ),
        migrations.RemoveConstraint(
            model_name='la_rrr_model',
            name='RRR_Unique',
        ),
        migrations.AddField(
            model_name='sl_group_party_members_model',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='user.party_model'),
        ),
    ]
