# Generated by Django 5.1 on 2025-07-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0329_sl_group_party_members_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_annotation_model',
            name='claiment_pid',
        ),
        migrations.RemoveField(
            model_name='admin_annotation_model',
            name='rrr_id',
        ),
        migrations.RemoveField(
            model_name='la_mortgage_model',
            name='mortgagor',
        ),
        migrations.RemoveField(
            model_name='la_mortgage_model',
            name='rrr_id',
        ),
        migrations.RemoveField(
            model_name='la_responsibility_model',
            name='party',
        ),
        migrations.RemoveField(
            model_name='la_responsibility_model',
            name='rrr_id',
        ),
        migrations.RemoveField(
            model_name='sl_admin_restrict_model',
            name='gov_party',
        ),
        migrations.RemoveField(
            model_name='sl_admin_restrict_model',
            name='rrr_id',
        ),
        migrations.RemoveField(
            model_name='sl_rights_liabilities_model',
            name='party',
        ),
        migrations.RemoveField(
            model_name='sl_rights_liabilities_model',
            name='rrr_id',
        ),
        migrations.DeleteModel(
            name='SL_Rights_Model',
        ),
        migrations.DeleteModel(
            name='Admin_Annotation_Model',
        ),
        migrations.DeleteModel(
            name='LA_Mortgage_Model',
        ),
        migrations.DeleteModel(
            name='LA_Responsibility_Model',
        ),
        migrations.DeleteModel(
            name='SL_Admin_Restrict_Model',
        ),
        migrations.DeleteModel(
            name='SL_Rights_Liabilities_Model',
        ),
    ]
