# Generated by Django 5.1 on 2025-07-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0330_remove_admin_annotation_model_claiment_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dep_id',
            field=models.IntegerField(),
        ),
    ]
