# Generated by Django 5.1 on 2025-07-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0331_user_emp_id_alter_user_dep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
