# Generated by Django 5.1 on 2025-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0332_alter_user_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sl_organization_model',
            name='contact_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sl_organization_model',
            name='org_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sl_organization_model',
            name='org_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
