# Generated by Django 5.1 on 2025-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0333_sl_organization_model_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sl_organization_model',
            name='director',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sl_organization_model',
            name='contact_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
