# Generated by Django 5.1 on 2025-07-11 17:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0335_alter_survey_rep_data_model_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
