# Generated by Django 5.1 on 2025-07-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0338_alter_survey_rep_data_model_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_permission_model',
            name='add',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='role_permission_model',
            name='delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='role_permission_model',
            name='edit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
