# Generated by Django 5.1 on 2025-07-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0339_alter_role_permission_model_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_permission_model',
            name='view',
            field=models.BooleanField(default=True),
        ),
    ]
