# Generated by Django 5.1 on 2025-07-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0340_alter_role_permission_model_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_list_model',
            name='add',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='permission_list_model',
            name='delete',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='permission_list_model',
            name='edit',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='permission_list_model',
            name='view',
            field=models.BooleanField(default=True),
        ),
    ]
