# Generated by Django 5.1 on 2025-07-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0341_permission_list_model_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission_list_model',
            name='edit',
            field=models.BooleanField(null=True),
        ),
    ]
