# Generated by Django 5.1 on 2025-07-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0342_alter_permission_list_model_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_permission_model',
            name='add',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='role_permission_model',
            name='delete',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='role_permission_model',
            name='edit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='role_permission_model',
            name='view',
            field=models.BooleanField(),
        ),
    ]
