# Generated by Django 5.1 on 2025-07-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0343_alter_role_permission_model_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_permission_model',
            name='remark',
        ),
    ]
