# Generated by Django 5.1 on 2025-07-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0344_remove_role_permission_model_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_permission_model',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
