# Generated by Django 5.1 on 2025-07-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0345_role_permission_model_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_permission_model',
            name='permission_id',
        ),
        migrations.RemoveField(
            model_name='role_permission_model',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='role_permission_model',
            name='role_id',
        ),
        migrations.DeleteModel(
            name='Permission_List_Model',
        ),
    ]
