# Generated by Django 5.1 on 2025-07-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0346_remove_role_permission_model_permission_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission_List_Model',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('permission_name', models.CharField(max_length=100)),
                ('view', models.BooleanField(default=True)),
                ('add', models.BooleanField(null=True)),
                ('edit', models.BooleanField(null=True)),
                ('delete', models.BooleanField(null=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'permission_list',
                'managed': True,
            },
        ),
    ]
