# Generated by Django 5.1 on 2025-07-16 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0347_permission_list_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_permission_model',
            name='permission_id',
            field=models.ForeignKey(db_column='permission_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.permission_list_model'),
        ),
        migrations.AddField(
            model_name='role_permission_model',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user_roles_model'),
        ),
    ]
