# Generated by Django 5.1 on 2025-07-16 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0348_role_permission_model_permission_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_permission_model',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='role_permission_model',
            name='permission_id',
            field=models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='user.permission_list_model'),
        ),
        migrations.AlterField(
            model_name='role_permission_model',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='user.user_roles_model'),
        ),
    ]
