# Generated by Django 5.1 on 2025-07-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0349_role_permission_model_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='org_id',
            field=models.IntegerField(null=True),
        ),
    ]
