# Generated by Django 5.1 on 2025-07-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0350_survey_rep_data_model_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_permission_model',
            name='remark',
        ),
    ]
