# Generated by Django 5.1 on 2025-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0351_remove_role_permission_model_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='gnd_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='org_id',
            field=models.IntegerField(),
        ),
    ]
