# Generated by Django 5.1 on 2025-07-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0352_alter_survey_rep_data_model_gnd_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_model',
            name='ass_div',
            field=models.IntegerField(null=True),
        ),
    ]
