# Generated by Django 5.1 on 2025-07-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0353_alter_assessment_model_ass_div'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='gnd_id',
            field=models.IntegerField(null=True),
        ),
    ]
