# Generated by Django 5.1 on 2025-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0354_alter_survey_rep_data_model_gnd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_ls_utinet_bu_model',
            name='drainage',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
