# Generated by Django 5.1 on 2025-07-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0355_la_ls_utinet_bu_model_drainage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Import_RasterData_Model',
        ),
        migrations.DeleteModel(
            name='Import_VectorDATA_Model',
        ),
    ]
