# Generated by Django 5.1 on 2025-08-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0356_delete_import_rasterdata_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_Active_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('active_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'user_last_active',
                'managed': True,
            },
        ),
    ]
