# Generated by Django 5.1 on 2025-08-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0357_last_active_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_permission_model',
            name='role_id',
        ),
    ]
