# Generated by Django 5.1 on 2025-08-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0359_role_permission_model_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_permission_model',
            name='role_id',
        ),
    ]
