# Generated by Django 5.1 on 2025-08-05 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0360_remove_role_permission_model_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_permission_model',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user_roles_model'),
            preserve_default=False,
        ),
    ]
