# Generated by Django 5.1 on 2025-08-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0361_role_permission_model_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sl_organization_model',
            name='dimension_2d_3d',
        ),
        migrations.RemoveField(
            model_name='sl_organization_model',
            name='party_id',
        ),
        migrations.AddField(
            model_name='sl_organization_model',
            name='subscription_plan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
