# Generated by Django 5.1 on 2025-08-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0362_remove_sl_organization_model_dimension_2d_3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sl_organization_model',
            name='users_limit',
            field=models.IntegerField(null=True),
        ),
    ]
