# Generated by Django 5.1 on 2025-08-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0363_sl_organization_model_users_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sl_organization_model',
            name='permit_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sl_organization_model',
            name='permit_start_date',
            field=models.DateField(null=True),
        ),
    ]
