# Generated by Django 5.1 on 2025-08-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0365_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_roles_model',
            name='role_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
