# Generated by Django 5.1 on 2025-08-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0366_user_roles_model_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles_model',
            name='role_type',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
