# Generated by Django 5.1 on 2025-08-17 05:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0367_alter_user_roles_model_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_location_model',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='org_location_model',
            name='dist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='org_location_model',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
