# Generated by Django 5.1 on 2025-08-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0368_alter_org_location_model_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_location_model',
            name='org_id',
            field=models.IntegerField(unique=True),
        ),
    ]
