# Generated by Django 5.1 on 2025-08-19 14:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0369_alter_org_location_model_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_area_model',
            name='org_area',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
