# Generated by Django 5.1 on 2025-08-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0370_alter_org_area_model_org_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_active_model',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
