# Generated by Django 5.1 on 2025-08-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0371_alter_last_active_model_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_list_model',
            name='type',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
