# Generated by Django 5.1 on 2025-08-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0372_permission_list_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission_list_model',
            name='view',
            field=models.BooleanField(null=True),
        ),
    ]
