# Generated by Django 5.1 on 2025-08-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0373_alter_permission_list_model_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_permission_model',
            name='view',
            field=models.BooleanField(null=True),
        ),
    ]
