# Generated by Django 5.1 on 2025-08-31 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0374_alter_role_permission_model_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
