# Generated by Django 5.1 on 2025-09-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0375_alter_survey_rep_data_model_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='acceptance_date',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='avl_status',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='exte_arch_ref',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='life_span_stamp',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='modifydate_acceptance_date',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='modifydate_exte_arch_ref',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='modifydate_life_span_stamp',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='modifydate_reference_no',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='party',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='reference_no',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='source_description',
        ),
    ]
