# Generated by Django 5.1 on 2025-09-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0376_remove_la_admin_source_model_acceptance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='code',
        ),
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='la_ba_unit_type',
        ),
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='party',
        ),
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='status',
        ),
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='su_id',
        ),
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='time_spec',
        ),
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='user_id',
        ),
    ]
