# Generated by Django 5.1 on 2025-09-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0377_remove_la_rrr_model_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sl_ba_unit_model',
            name='sl_ba_unit_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sl_ba_unit_model',
            name='sl_ba_unit_type',
            field=models.CharField(max_length=30),
        ),
    ]
