# Generated by Django 5.1 on 2025-09-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0378_alter_sl_ba_unit_model_sl_ba_unit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='la_rrr_model',
            name='admin_source_id',
        ),
        migrations.AddField(
            model_name='la_admin_source_model',
            name='rrr_id',
            field=models.ForeignKey(db_column='rrr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model'),
        ),
    ]
