# Generated by Django 5.1 on 2025-09-20 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0379_remove_la_rrr_model_admin_source_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party_Roles_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_role_type', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.IntegerField()),
                ('pid', models.ForeignKey(db_column='pid', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.party_model')),
                ('rrr_id', models.ForeignKey(db_column='rrr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.la_rrr_model')),
            ],
            options={
                'db_table': 'sl_party_roles',
                'managed': True,
            },
        ),
    ]
