# Generated by Django 5.1 on 2025-09-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0380_party_roles_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party_model',
            name='ref_id',
        ),
        migrations.RemoveField(
            model_name='party_model',
            name='sl_group_party_id',
        ),
        migrations.RemoveField(
            model_name='sl_group_party_members_model',
            name='group_name',
        ),
    ]
