# Generated by Django 5.1 on 2025-10-16 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0381_remove_party_model_ref_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='la_admin_source_model',
            old_name='user_id',
            new_name='done_by',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='ba_unit_id',
        ),
        migrations.RemoveField(
            model_name='la_admin_source_model',
            name='rrr_id',
        ),
        migrations.AddField(
            model_name='la_rrr_model',
            name='admin_source_id',
            field=models.ForeignKey(db_column='admin_source_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.la_admin_source_model'),
        ),
    ]
