# Generated by Django 5.1 on 2025-10-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0382_rename_user_id_la_admin_source_model_done_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_rrr_model',
            name='pid',
            field=models.ForeignKey(db_column='pid', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.party_model'),
        ),
    ]
