# Generated by Django 5.1 on 2026-02-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0383_la_rrr_model_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_ls_utinet_bu_model',
            name='drainage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
