# Generated by Django 5.1 on 2026-02-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0384_alter_la_ls_utinet_bu_model_drainage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic_Attribute_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('su_id', models.IntegerField()),
                ('section_key', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dynamic_attribute',
                'managed': True,
            },
        ),
    ]
