# Generated by Django 5.1 on 2026-02-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0385_dynamic_attribute_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='registration_date',
            field=models.DateField(null=True),
        ),
    ]
