# Generated by Django 5.1 on 2026-02-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0386_add_registration_date_to_land_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_rrr_model',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='la_rrr_model',
            name='rrr_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='la_rrr_model',
            name='time_begin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='la_rrr_model',
            name='time_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='residence_info_model',
            name='su_id',
            field=models.ForeignKey(db_column='su_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.CreateModel(
            name='LA_Level_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(db_column='content_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.lst_su_sl_levelcontenttype_19_model')),
                ('register_type', models.ForeignKey(db_column='register_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.lst_su_sl_regestertype_20_model')),
                ('structure_type', models.ForeignKey(db_column='structure_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.lst_su_sl_structuretype_21_model')),
            ],
            options={
                'db_table': 'la_level',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='la_spatial_unit_model',
            name='level',
            field=models.ForeignKey(db_column='level_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.la_level_model'),
        ),
    ]
