# Generated by Django 5.1 on 2026-02-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0387_la_rrr_model_description_la_rrr_model_rrr_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_LS_Zoning_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zoning_category', models.CharField(max_length=10, null=True)),
                ('max_building_height', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('max_coverage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('max_far', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('setback_front', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('setback_rear', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('setback_side', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('special_overlay', models.CharField(max_length=255, null=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_zoning',
                'managed': True,
            },
        ),
    ]
