# Generated by Django 5.1 on 2026-02-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0388_la_ls_zoning_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='local_auth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
