# Generated by Django 5.1 on 2026-02-21 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0389_la_ls_land_unit_model_local_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_model',
            name='land_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='assessment_model',
            name='market_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='assessment_model',
            name='tax_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_build_unit_model',
            name='condition',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_build_unit_model',
            name='construction_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='la_ls_build_unit_model',
            name='registration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='la_ls_build_unit_model',
            name='structure_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='LA_LS_Physical_Env_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elevation', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('slope', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('soil_type', models.CharField(max_length=20, null=True)),
                ('flood_zone', models.BooleanField(null=True)),
                ('vegetation_cover', models.CharField(max_length=255, null=True)),
                ('su_id', models.OneToOneField(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ls_physical_env',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_RRR_Responsibility_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rrr_responsibility_type', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('time_begin', models.DateField(null=True)),
                ('time_end', models.DateField(null=True)),
                ('rrr_id', models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='user.la_rrr_model')),
            ],
            options={
                'db_table': 'la_rrr_responsibility',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LA_RRR_Restriction_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rrr_restriction_type', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('time_begin', models.DateField(null=True)),
                ('time_end', models.DateField(null=True)),
                ('rrr_id', models.ForeignKey(db_column='rrr_id', on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='user.la_rrr_model')),
            ],
            options={
                'db_table': 'la_rrr_restriction',
                'managed': True,
            },
        ),
    ]
