# Generated by Django 5.1 on 2026-02-22 10:14

from django.db import migrations


NEW_PERMISSIONS = [
    # ── Land Tab – Physical Environment (43–47) ─────────────────────────
    (43, 'Land Tab', 'Physical Environment', 'Elevation',        3),
    (44, 'Land Tab', 'Physical Environment', 'Slope',            3),
    (45, 'Land Tab', 'Physical Environment', 'Soil Type',        3),
    (46, 'Land Tab', 'Physical Environment', 'Flood Zone',       3),
    (47, 'Land Tab', 'Physical Environment', 'Vegetation Cover', 3),

    # ── Land Tab – Zoning Information (48–55) ───────────────────────────
    (48, 'Land Tab', 'Zoning Information', 'Zoning Category',       3),
    (49, 'Land Tab', 'Zoning Information', 'Max Building Height',   3),
    (50, 'Land Tab', 'Zoning Information', 'Max Coverage',          3),
    (51, 'Land Tab', 'Zoning Information', 'Max FAR',               3),
    (52, 'Land Tab', 'Zoning Information', 'Front Setback',         3),
    (53, 'Land Tab', 'Zoning Information', 'Rear Setback',          3),
    (54, 'Land Tab', 'Zoning Information', 'Side Setback',          3),
    (55, 'Land Tab', 'Zoning Information', 'Special Overlay',       3),

    # ── Land Tab – Assessment Information additions (56–58) ─────────────
    (56, 'Land Tab', 'Assessment Information', 'Land Value',    3),
    (57, 'Land Tab', 'Assessment Information', 'Market Value',  3),
    (58, 'Land Tab', 'Assessment Information', 'Tax Status',    3),

    # ── Building Tab – Administrative Information additions (155–158) ────
    (155, 'Building Tab', 'Administrative Information', 'Registration Date',  3),
    (156, 'Building Tab', 'Administrative Information', 'Construction Year',  3),
    (157, 'Building Tab', 'Administrative Information', 'Structure Type',     3),
    (158, 'Building Tab', 'Administrative Information', 'Condition',          3),

    # ── Building Tab – Assessment Information additions (159–161) ────────
    (159, 'Building Tab', 'Assessment Information', 'Land Value',   3),
    (160, 'Building Tab', 'Assessment Information', 'Market Value', 3),
    (161, 'Building Tab', 'Assessment Information', 'Tax Status',   3),
]


def add_permissions(apps, schema_editor):
    Permission_List_Model = apps.get_model('user', 'Permission_List_Model')
    existing_ids = set(
        Permission_List_Model.objects.values_list('permission_id', flat=True)
    )
    to_create = [
        Permission_List_Model(
            permission_id=pid,
            category=cat,
            sub_category=sub,
            permission_name=name,
            view=True,
            add=True,
            edit=True,
            delete=True,
            status=True,
            type=t,
        )
        for pid, cat, sub, name, t in NEW_PERMISSIONS
        if pid not in existing_ids
    ]
    if to_create:
        Permission_List_Model.objects.bulk_create(to_create)


def remove_permissions(apps, schema_editor):
    Permission_List_Model = apps.get_model('user', 'Permission_List_Model')
    ids = [pid for pid, *_ in NEW_PERMISSIONS]
    Permission_List_Model.objects.filter(permission_id__in=ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0390_assessment_model_land_value_and_more'),
    ]

    operations = [
        migrations.RunPython(add_permissions, remove_permissions),
    ]
