# Generated by Django 5.1 on 2026-02-25 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0391_add_new_ladm_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_spartialunit_attrib_model',
            name='su_id',
            field=models.ForeignKey(db_column='su_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='su_id',
            field=models.ForeignKey(db_column='su_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.la_spatial_unit_model', to_field='su_id'),
        ),
        migrations.CreateModel(
            name='LA_BAUnit_SpatialUnit_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(default='PRIMARY', max_length=20, null=True)),
                ('ba_unit', models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model')),
                ('su', models.ForeignKey(db_column='su_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_spatial_unit_model', to_field='su_id')),
            ],
            options={
                'db_table': 'la_ba_unit_spatial_unit',
                'managed': True,
                'unique_together': {('ba_unit', 'su')},
            },
        ),
    ]
