# Generated by Django 5.1 on 2026-02-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0393_move_share_to_party_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='area',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='boundary_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='crs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='dimension_2d_3d',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='perimeter',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='la_spatial_unit_model',
            name='parcel_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
