# Generated by Django 5.1 on 2026-03-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0394_la_ls_land_unit_model_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sl_ba_unit_model',
            name='org_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sl_ba_unit_model',
            name='role_type',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
