# Generated by Django 5.1 on 2026-03-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0395_add_org_role_to_sl_ba_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_RRR_Document_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_source', models.ForeignKey(db_column='admin_source_id', on_delete=django.db.models.deletion.CASCADE, to='user.la_admin_source_model')),
                ('ba_unit', models.ForeignKey(db_column='ba_unit_id', on_delete=django.db.models.deletion.CASCADE, to='user.sl_ba_unit_model')),
            ],
            options={
                'db_table': 'la_rrr_document',
                'managed': True,
            },
        ),
    ]
