# Generated by Django 5.1 on 2026-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0410_drop_unused_fields_session4'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_info_model',
            name='date_valuation',
            field=models.DateTimeField(null=True),
        ),
    ]
