# Generated by Django 5.1 on 2026-03-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0412_fix_tax_info_date_valuation_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='ref_id',
            field=models.IntegerField(db_column='ref_ids', null=True),
        ),
    ]
