# Generated by Django 5.1 on 2026-03-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0418_drop_org_id_role_type_from_sl_ba_unit'),
    ]

    operations = [
        # Sync Django model state only: 0418 already dropped these via RunSQL,
        # so the DB columns are gone — just update the migration state.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='sl_ba_unit_model',
                    name='org_id',
                ),
                migrations.RemoveField(
                    model_name='sl_ba_unit_model',
                    name='role_type',
                ),
            ],
        ),
        # Add geom column to org_location — it is in Django's model state (from migration 0278)
        # but was never actually created in this local DB instance.
        migrations.RunSQL(
            sql="""
                ALTER TABLE org_location
                ADD COLUMN IF NOT EXISTS geom geometry(Geometry, 4326);
            """,
            reverse_sql="""
                ALTER TABLE org_location DROP COLUMN IF EXISTS geom;
            """,
        ),
    ]
