# Generated by Django 5.1 on 2026-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0421_ensure_survey_rep_gnd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='boundary_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='crs',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='perimeter',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='tenure_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='la_spatial_unit_model',
            name='parcel_status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
