# Generated by Django 5.1 on 2026-03-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0422_add_land_unit_spatial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='adjacent_parcels',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='child_parcels',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='parent_parcel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='la_ls_land_unit_model',
            name='part_of_estate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
