# Generated by Django 5.1 on 2026-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0424_la_admin_source_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_model',
            name='assessment_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
