# Generated by Django 5.1 on 2026-03-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0426_enforce_geom_not_null_in_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey_rep_data_model',
            old_name='area',
            new_name='calculated_area',
        ),
        migrations.RenameField(
            model_name='survey_rep_geom_history_model',
            old_name='area',
            new_name='calculated_area',
        ),
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='legal_area',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='survey_rep_data_model',
            name='legal_area_unit',
            field=models.CharField(choices=[('sqm', 'sq.m'), ('acres', 'Acres'), ('perches', 'Perches')], max_length=20, null=True),
        ),
    ]
