# Generated by Django 5.1 on 2026-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0432_enforce_gnd_geom_type_and_notnull'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sl_gnd_10m_model',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='gnd_id',
            field=models.IntegerField(),
        ),
    ]
