# Generated by Django 5.1 on 2026-03-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0437_rebackfill_survey_rep_gnd_id'),
    ]

    operations = [
        # Drop the GIST index created in 0436 before changing the column type,
        # since varchar has no default GIST operator class.
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS survey_rep_ref_coord_gist_idx;

                ALTER TABLE survey_rep
                    ALTER COLUMN reference_coordinate TYPE varchar(50)
                    USING NULL;

                ALTER TABLE survey_rep_geom_history
                    ALTER COLUMN reference_coordinate TYPE varchar(50)
                    USING NULL;
            """,
            reverse_sql="""
                ALTER TABLE survey_rep
                    ALTER COLUMN reference_coordinate TYPE geometry
                    USING NULL;

                ALTER TABLE survey_rep_geom_history
                    ALTER COLUMN reference_coordinate TYPE geometry
                    USING NULL;

                CREATE INDEX IF NOT EXISTS survey_rep_ref_coord_gist_idx
                    ON survey_rep USING GIST (reference_coordinate)
                    WHERE reference_coordinate IS NOT NULL;
            """,
        ),
        # Keep Django's migration state in sync with the CharField definition.
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='reference_coordinate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey_rep_geom_history_model',
            name='reference_coordinate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
