# Generated by Django 5.1 on 2026-03-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0441_allow_null_geom_history_reference_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_active_model',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='gnd_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='layer_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='org_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dep_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='org_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user_roles_model',
            name='org_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='role_permission_model',
            index=models.Index(fields=['role_id', 'permission_id'], name='idx_roleperm_role_perm'),
        ),
    ]
