# Generated by Django 5.1 on 2026-03-21 05:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Both la_party_type and sl_party_type were absent from the sl_party DB table
    but are defined in the Django model and required for operations.
    This migration adds the columns to the DB only; Django's migration state
    already tracks these fields from earlier migrations.
    No other tables (survey_rep, sl_gnd_10m, etc.) are touched.
    """

    dependencies = [
        ('user', '0442_add_hot_column_indexes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Add the two missing columns to sl_party in the actual database.
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE sl_party
                            ADD COLUMN IF NOT EXISTS la_party_type VARCHAR(255),
                            ADD COLUMN IF NOT EXISTS sl_party_type VARCHAR(255);
                    """,
                    reverse_sql="""
                        ALTER TABLE sl_party
                            DROP COLUMN IF EXISTS la_party_type,
                            DROP COLUMN IF EXISTS sl_party_type;
                    """,
                ),
            ],
            # Django state already has these fields — no state change needed.
            state_operations=[],
        ),
    ]
