# Generated by Django 5.1 on 2026-03-21 05:03
#
# Migration 0443 already added sl_party_type to the DB and preserved the
# Django state, so this migration is now a deliberate no-op.
# It is kept to maintain the migration chain integrity.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0443_remove_party_model_sl_party_type'),
    ]

    operations = [
        # sl_party_type already exists in both the DB (added by 0443) and
        # Django's migration state — nothing to do here.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[],
        ),
    ]
