# Generated by Django 5.1 on 2026-03-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0457_survey_rep_su_id_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='gnd_id',
            field=models.IntegerField(blank=True, db_column='gndid', db_index=True, null=True),
        ),
    ]
