# Generated by Django 5.1 on 2026-04-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0458_gnd_id_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='gnd_id',
            field=models.IntegerField(blank=True, db_column='gnd_id', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey_rep_data_model',
            name='org_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
