# Generated by Django 5.1 on 2026-04-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0459_alter_survey_rep_data_model_gnd_id_and_more'),
        ('user', '0460_rename_gndid_to_gnd_id'),
    ]

    operations = [
    ]
